import type { StaticAmenityItem } from './amenities-data-salon';

export const SURROUNDINGS_AMENITIES: StaticAmenityItem[] = [
  // --- LAMBESC ---
  {
    name: 'Collège Jean Guéhenno Lambesc',
    category: 'education',
    subtype: 'college',
    lat: 43.6528,
    lon: 5.258,
    address: 'Chemin de Saint-Pierre, 13410 Lambesc',
    badge: 'Collège Public',
  },
  {
    name: 'École Primaire & Maternelle Van Gogh',
    category: 'education',
    subtype: 'primaire',
    lat: 43.655,
    lon: 5.2625,
    address: 'Avenue de la Résistance, 13410 Lambesc',
    badge: 'Groupe Scolaire Public',
  },
  {
    name: 'Intermarché Super Lambesc',
    category: 'commerce',
    subtype: 'supermarche',
    lat: 43.6515,
    lon: 5.255,
    address: 'Route Nationale 7, 13410 Lambesc',
    badge: 'Supermarché & Drive',
  },
  {
    name: 'Netto Lambesc',
    category: 'commerce',
    subtype: 'supermarche',
    lat: 43.6508,
    lon: 5.2538,
    address: 'Route de Pelissanne, 13410 Lambesc',
    badge: 'Supermarché Hard Discount',
  },
  {
    name: 'Supérette Utile Lambesc',
    category: 'commerce',
    subtype: 'superette',
    lat: 43.654,
    lon: 5.261,
    address: 'Boulevard de la République, 13410 Lambesc',
    badge: 'Supérette Centre',
  },
  {
    name: 'Pharmacie du Jacquemart',
    category: 'sante',
    subtype: 'pharmacie',
    lat: 43.6545,
    lon: 5.2615,
    address: 'Place Jean Jaurès, 13410 Lambesc',
    badge: 'Pharmacie',
  },
  {
    name: 'École Maternelle Jacques Prévert',
    category: 'education',
    subtype: 'maternelle',
    lat: 43.6538,
    lon: 5.2605,
    address: 'Avenue de Bad-Säckingen, 13410 Lambesc',
    badge: 'Maternelle Publique',
  },
  {
    name: 'Boulangerie Pâtisserie du Jacquemart',
    category: 'commerce',
    subtype: 'boulangerie',
    lat: 43.6542,
    lon: 5.2612,
    address: 'Boulevard de la République, 13410 Lambesc',
    badge: 'Boulangerie Artisanale',
  },
  {
    name: 'Complexe Sportif du COSEC Lambesc',
    category: 'sport',
    subtype: 'complexe_sportif',
    lat: 43.6518,
    lon: 5.2592,
    address: 'Chemin de Saint-Pierre, 13410 Lambesc',
    badge: 'Gymnase & Terrains Multisports',
  },
  {
    name: 'Arrêt de Bus Lambesc Centre (Lignes Métropole & Scolaires)',
    category: 'transport',
    subtype: 'bus',
    lat: 43.654,
    lon: 5.2618,
    address: 'Boulevard de la République, 13410 Lambesc',
    badge: 'Bus Lignes 240, 241, 52',
  },
  {
    name: 'Cabinet Médical de Lambesc',
    category: 'sante',
    subtype: 'medecin',
    lat: 43.6535,
    lon: 5.262,
    address: 'Avenue du 8 Mai 1945, 13410 Lambesc',
    badge: 'Médecins Généralistes',
  },

  // --- LANÇON-PROVENCE ---
  {
    name: 'Collège Lucie Aubrac Lançon',
    category: 'education',
    subtype: 'college',
    lat: 43.5962,
    lon: 5.1245,
    address: 'Chemin des Bœufs, 13680 Lançon-Provence',
    badge: 'Collège Public',
  },
  {
    name: 'École Primaire Frédéric Mistral',
    category: 'education',
    subtype: 'primaire',
    lat: 43.5918,
    lon: 5.127,
    address: 'Boulevard Victor Hugo, 13680 Lançon-Provence',
    badge: 'Primaire Publique',
  },
  {
    name: 'École Maternelle Marie Mauron',
    category: 'education',
    subtype: 'maternelle',
    lat: 43.5935,
    lon: 5.129,
    address: 'Avenue de la République, 13680 Lançon-Provence',
    badge: 'Maternelle Publique',
  },
  {
    name: 'Intermarché Contact Lançon-Provence',
    category: 'commerce',
    subtype: 'supermarche',
    lat: 43.5902,
    lon: 5.1255,
    address: 'Route de Pelissanne, 13680 Lançon-Provence',
    badge: 'Supermarché & Carburant',
  },
  {
    name: 'Supérette Utile Lançon-Provence',
    category: 'commerce',
    subtype: 'superette',
    lat: 43.5922,
    lon: 5.1278,
    address: 'Place du Champ de Mars, 13680 Lançon-Provence',
    badge: 'Supérette Proximité',
  },
  {
    name: 'Pharmacie des Romarins',
    category: 'sante',
    subtype: 'pharmacie',
    lat: 43.5915,
    lon: 5.1265,
    address: 'Rue de la République, 13680 Lançon-Provence',
    badge: 'Pharmacie',
  },

  // --- GRANS ---
  {
    name: 'École Primaire & Maternelle Georges Brassens',
    category: 'education',
    subtype: 'primaire',
    lat: 43.6095,
    lon: 5.062,
    address: 'Rue des Écoles, 13450 Grans',
    badge: 'Groupe Scolaire Public',
  },
  {
    name: 'Supérette Proxi Grans',
    category: 'commerce',
    subtype: 'superette',
    lat: 43.6085,
    lon: 5.0645,
    address: 'Place de la République, 13450 Grans',
    badge: 'Supérette Centre',
  },
  {
    name: 'Boulangerie Le Fournil de Grans',
    category: 'commerce',
    subtype: 'boulangerie',
    lat: 43.6082,
    lon: 5.0638,
    address: 'Rue Fernand Pauriol, 13450 Grans',
    badge: 'Boulangerie Artisanale',
  },
  {
    name: 'Pharmacie de Grans',
    category: 'sante',
    subtype: 'pharmacie',
    lat: 43.608,
    lon: 5.064,
    address: 'Cours Camille Pelletan, 13450 Grans',
    badge: 'Pharmacie',
  },

  // --- SAINT-CHAMAS & MIRAMAS (Gares & Transports Express) ---
  {
    name: 'Gare SNCF de Miramas (TGV & TER)',
    category: 'transport',
    subtype: 'gare',
    lat: 43.582,
    lon: 5.0018,
    address: 'Place de la Gare, 13140 Miramas',
    badge: 'Gare TGV & TER Provence',
  },
  {
    name: 'Gare SNCF de Saint-Chamas (TER)',
    category: 'transport',
    subtype: 'gare',
    lat: 43.5488,
    lon: 5.0342,
    address: 'Avenue de la Gare, 13250 Saint-Chamas',
    badge: 'Gare TER Ligne Marseille - Avignon',
  },

  // --- VILLAGES DU MASSIF : AURONS, ALLEINS, VERNÈGUES, LA BARBEN ---
  {
    name: 'École Primaire Municipale Aurons',
    category: 'education',
    subtype: 'primaire',
    lat: 43.6645,
    lon: 5.1632,
    address: 'Le Village, 13121 Aurons',
    badge: 'École Communale',
  },
  {
    name: 'École Primaire Publique Alleins',
    category: 'education',
    subtype: 'primaire',
    lat: 43.7045,
    lon: 5.1615,
    address: 'Rue des Écoles, 13980 Alleins',
    badge: 'École Communale',
  },
  {
    name: 'École Primaire de Vernègues - Cazan',
    category: 'education',
    subtype: 'primaire',
    lat: 43.6875,
    lon: 5.172,
    address: 'Hameau de Cazan, 13116 Vernègues',
    badge: 'École Publique',
  },
  {
    name: 'Parc Zoologique & Château de La Barben',
    category: 'sport',
    subtype: 'parc',
    lat: 43.6302,
    lon: 5.2055,
    address: 'Route du Château, 13330 La Barben',
    badge: 'Grand Parc de Loisirs',
  },
];
