import type { AmenityCategory, AmenitySubtype } from './amenities';

export interface StaticAmenityItem {
  name: string;
  category: AmenityCategory;
  subtype: AmenitySubtype;
  lat: number;
  lon: number;
  address: string;
  badge?: string;
  phone?: string;
}

export const SALON_DE_PROVENCE_AMENITIES: StaticAmenityItem[] = [
  // --- ÉDUCATION : COLLÈGES & LYCÉES ---
  {
    name: "Collège Joseph d'Arbaud",
    category: 'education',
    subtype: 'college',
    lat: 43.6365,
    lon: 5.088,
    address: '215 Boulevard de la République, 13300 Salon-de-Provence',
    badge: 'Collège Public',
    phone: '04 90 56 12 73',
  },
  {
    name: 'Collège Jean Moulin',
    category: 'education',
    subtype: 'college',
    lat: 43.6415,
    lon: 5.1062,
    address: 'Avenue Maréchal de Lattre de Tassigny, 13300 Salon-de-Provence',
    badge: 'Collège Public',
    phone: '04 90 56 28 85',
  },
  {
    name: 'Collège de Craponne',
    category: 'education',
    subtype: 'college',
    lat: 43.645,
    lon: 5.092,
    address: '148 Rue de Craponne, 13300 Salon-de-Provence',
    badge: 'Collège Public',
    phone: '04 90 56 13 45',
  },
  {
    name: 'Collège Privé La Présentation',
    category: 'education',
    subtype: 'college',
    lat: 43.6395,
    lon: 5.0922,
    address: '106 Boulevard Ledru-Rollin, 13300 Salon-de-Provence',
    badge: 'Collège Privé',
    phone: '04 90 56 04 28',
  },
  {
    name: 'Collège Privé Saint-Norbert',
    category: 'education',
    subtype: 'college',
    lat: 43.638,
    lon: 5.0945,
    address: 'Rue de la Fraternité, 13300 Salon-de-Provence',
    badge: 'Collège Privé',
  },
  {
    name: 'Lycée Général & Technologique Adam de Craponne',
    category: 'education',
    subtype: 'lycee',
    lat: 43.6412,
    lon: 5.0895,
    address: 'Boulevard Ledru-Rollin, 13300 Salon-de-Provence',
    badge: 'Lycée Public',
  },
  {
    name: "Lycée Général & Technologique de l'Empéri",
    category: 'education',
    subtype: 'lycee',
    lat: 43.6425,
    lon: 5.0968,
    address: 'Montée du Puech, 13300 Salon-de-Provence',
    badge: 'Lycée Public',
  },
  {
    name: 'Lycée Professionnel Le Rocher',
    category: 'education',
    subtype: 'lycee',
    lat: 43.6468,
    lon: 5.0762,
    address: 'Allée de la Crau, 13300 Salon-de-Provence',
    badge: 'Lycée Public',
  },

  // --- ÉDUCATION : ÉCOLES MATERNELLES & PRIMAIRES ---
  {
    name: 'École Maternelle Georges Guynemer',
    category: 'education',
    subtype: 'maternelle',
    lat: 43.6358,
    lon: 5.0875,
    address: 'Avenue Georges Guynemer, 13300 Salon-de-Provence',
    badge: 'Maternelle Publique',
  },
  {
    name: 'École Élémentaire Georges Guynemer',
    category: 'education',
    subtype: 'primaire',
    lat: 43.6355,
    lon: 5.0872,
    address: 'Avenue Georges Guynemer, 13300 Salon-de-Provence',
    badge: 'Primaire Publique',
  },
  {
    name: 'École Maternelle Lurian',
    category: 'education',
    subtype: 'maternelle',
    lat: 43.6442,
    lon: 5.11,
    address: 'Chemin de Lurian, 13300 Salon-de-Provence',
    badge: 'Maternelle Publique',
  },
  {
    name: 'École Élémentaire Lurian',
    category: 'education',
    subtype: 'primaire',
    lat: 43.6446,
    lon: 5.1105,
    address: 'Chemin de Lurian, 13300 Salon-de-Provence',
    badge: 'Primaire Publique',
  },
  {
    name: 'École Maternelle Les Bressons',
    category: 'education',
    subtype: 'maternelle',
    lat: 43.6492,
    lon: 5.0955,
    address: 'Chemin des Bressons, 13300 Salon-de-Provence',
    badge: 'Maternelle Publique',
  },
  {
    name: 'École Élémentaire Les Bressons',
    category: 'education',
    subtype: 'primaire',
    lat: 43.6495,
    lon: 5.0958,
    address: 'Chemin des Bressons, 13300 Salon-de-Provence',
    badge: 'Primaire Publique',
  },
  {
    name: 'École Maternelle Pavillon',
    category: 'education',
    subtype: 'maternelle',
    lat: 43.6402,
    lon: 5.0915,
    address: 'Boulevard Ledru-Rollin, 13300 Salon-de-Provence',
    badge: 'Maternelle Publique',
  },
  {
    name: 'École Élémentaire Saint-Jean',
    category: 'education',
    subtype: 'primaire',
    lat: 43.6382,
    lon: 5.0892,
    address: 'Boulevard de la République, 13300 Salon-de-Provence',
    badge: 'Primaire Publique',
  },
  {
    name: 'École Maternelle & Primaire La Bastide Haute',
    category: 'education',
    subtype: 'primaire',
    lat: 43.6305,
    lon: 5.0842,
    address: 'Chemin de la Bastide Haute, 13300 Salon-de-Provence',
    badge: 'Groupe Scolaire Public',
  },
  {
    name: 'Crèche Municipale Les Farfadets',
    category: 'education',
    subtype: 'creche',
    lat: 43.639,
    lon: 5.091,
    address: 'Avenue Paul Cézanne, 13300 Salon-de-Provence',
    badge: 'Crèche Municipale',
  },

  // --- COMMERCES : SUPERMARCHÉS ---
  {
    name: 'Supermarché Lidl République',
    category: 'commerce',
    subtype: 'supermarche',
    lat: 43.6375,
    lon: 5.0872,
    address: 'Boulevard de la République, 13300 Salon-de-Provence',
    badge: 'Supermarché Discount',
  },
  {
    name: 'Carrefour Market Place Morgan',
    category: 'commerce',
    subtype: 'supermarche',
    lat: 43.6405,
    lon: 5.0935,
    address: 'Place Morgan, 13300 Salon-de-Provence',
    badge: 'Supermarché Centre',
  },
  {
    name: 'Intermarché Super & Drive Bel-Air',
    category: 'commerce',
    subtype: 'supermarche',
    lat: 43.6483,
    lon: 5.0712,
    address: 'Allée de la Crau, 13300 Salon-de-Provence',
    badge: 'Supermarché & Drive',
  },
  {
    name: 'Intermarché Hyper Les Viougues',
    category: 'commerce',
    subtype: 'supermarche',
    lat: 43.6331,
    lon: 5.1052,
    address: '111 Boulevard Reine Jeanne, 13300 Salon-de-Provence',
    badge: 'Hypermarché',
  },
  {
    name: 'E.Leclerc Salon-de-Provence',
    category: 'commerce',
    subtype: 'supermarche',
    lat: 43.6455,
    lon: 5.0988,
    address: 'Boulevard du Roi René, 13300 Salon-de-Provence',
    badge: 'Hypermarché',
  },
  {
    name: "Carrefour Market Route d'Arles",
    category: 'commerce',
    subtype: 'supermarche',
    lat: 43.6438,
    lon: 5.0781,
    address: 'Avenue de la 1ère DFL, 13300 Salon-de-Provence',
    badge: 'Supermarché',
  },
  {
    name: 'Monoprix Salon-de-Provence',
    category: 'commerce',
    subtype: 'supermarche',
    lat: 43.6402,
    lon: 5.0965,
    address: '35 Cours Victor Hugo, 13300 Salon-de-Provence',
    badge: 'Supermarché Centre',
  },
  {
    name: 'Biocoop Salon-de-Provence',
    category: 'commerce',
    subtype: 'supermarche',
    lat: 43.6369,
    lon: 5.0865,
    address: 'Boulevard de la République, 13300 Salon-de-Provence',
    badge: 'Magasin Bio',
  },
  {
    name: 'Grand Frais Salon-de-Provence',
    category: 'commerce',
    subtype: 'supermarche',
    lat: 43.6495,
    lon: 5.0701,
    address: 'Allée des Joncs, 13300 Salon-de-Provence',
    badge: 'Primeur & Produits Frais',
  },

  // --- COMMERCES : SUPÉRETTES & PROXIMITÉ ---
  {
    name: 'Carrefour City Salon Gambetta',
    category: 'commerce',
    subtype: 'superette',
    lat: 43.6398,
    lon: 5.0982,
    address: 'Place Gambetta, 13300 Salon-de-Provence',
    badge: 'Supérette 7j/7',
  },
  {
    name: 'Carrefour Express Boulevard Foch',
    category: 'commerce',
    subtype: 'superette',
    lat: 43.6389,
    lon: 5.0951,
    address: 'Boulevard Foch, 13300 Salon-de-Provence',
    badge: 'Supérette Proximité',
  },
  {
    name: 'Spar Salon Nostradamus',
    category: 'commerce',
    subtype: 'superette',
    lat: 43.6421,
    lon: 5.0925,
    address: '180 Boulevard Nostradamus, 13300 Salon-de-Provence',
    badge: 'Supérette',
  },
  {
    name: 'Vival Salon Leclerc',
    category: 'commerce',
    subtype: 'superette',
    lat: 43.6342,
    lon: 5.0928,
    address: 'Avenue Maréchal Leclerc, 13300 Salon-de-Provence',
    badge: 'Alimentation Proximité',
  },
  {
    name: 'Petit Casino Kennedy',
    category: 'commerce',
    subtype: 'superette',
    lat: 43.6379,
    lon: 5.0991,
    address: 'Rue des Frères Kennedy, 13300 Salon-de-Provence',
    badge: 'Supérette',
  },
  {
    name: 'Épicerie Alimentation Générale Guynemer',
    category: 'commerce',
    subtype: 'superette',
    lat: 43.6361,
    lon: 5.0892,
    address: 'Avenue Georges Guynemer, 13300 Salon-de-Provence',
    badge: 'Épicerie de Quartier',
  },
  {
    name: 'Boulangerie Pâtisserie Guynemer',
    category: 'commerce',
    subtype: 'boulangerie',
    lat: 43.636,
    lon: 5.0885,
    address: 'Avenue Georges Guynemer, 13300 Salon-de-Provence',
    badge: 'Boulangerie Artisanale',
  },
  {
    name: 'Boulangerie Saint-Côme',
    category: 'commerce',
    subtype: 'boulangerie',
    lat: 43.6372,
    lon: 5.0878,
    address: 'Boulevard de la République, 13300 Salon-de-Provence',
    badge: 'Boulangerie Artisanale',
  },
  {
    name: 'Maison Jouval Place Morgan',
    category: 'commerce',
    subtype: 'boulangerie',
    lat: 43.6402,
    lon: 5.0938,
    address: 'Place Morgan, 13300 Salon-de-Provence',
    badge: 'Boulangerie & Pâtisserie',
  },
  {
    name: 'Marché Provençal de Salon-de-Provence',
    category: 'commerce',
    subtype: 'marche',
    lat: 43.6408,
    lon: 5.094,
    address: 'Place Morgan, 13300 Salon-de-Provence',
    badge: 'Mercredi & Samedi matin',
  },

  // --- SANTÉ & SOINS ---
  {
    name: 'Pharmacie Guynemer',
    category: 'sante',
    subtype: 'pharmacie',
    lat: 43.6362,
    lon: 5.0888,
    address: '63 Avenue Georges Guynemer, 13300 Salon-de-Provence',
    badge: 'Pharmacie',
    phone: '04 90 56 08 21',
  },
  {
    name: 'Pharmacie Saint-Côme',
    category: 'sante',
    subtype: 'pharmacie',
    lat: 43.637,
    lon: 5.0875,
    address: 'Boulevard de la République, 13300 Salon-de-Provence',
    badge: 'Pharmacie',
  },
  {
    name: 'Pharmacie de la Place Morgan',
    category: 'sante',
    subtype: 'pharmacie',
    lat: 43.6405,
    lon: 5.0942,
    address: 'Place Morgan, 13300 Salon-de-Provence',
    badge: 'Pharmacie',
  },
  {
    name: 'Pharmacie Centrale Victor Hugo',
    category: 'sante',
    subtype: 'pharmacie',
    lat: 43.6401,
    lon: 5.0968,
    address: 'Cours Victor Hugo, 13300 Salon-de-Provence',
    badge: 'Pharmacie',
  },
  {
    name: 'Centre Hospitalier Général de Salon-de-Provence',
    category: 'sante',
    subtype: 'hopital',
    lat: 43.6385,
    lon: 5.1042,
    address: '207 Avenue Julien Fabre, 13300 Salon-de-Provence',
    badge: 'Hôpital & Urgences 24/7',
    phone: '04 90 44 91 00',
  },
  {
    name: 'Clinique Chirurgicale Vignoli',
    category: 'sante',
    subtype: 'hopital',
    lat: 43.6428,
    lon: 5.0915,
    address: 'Avenue de Craponne, 13300 Salon-de-Provence',
    badge: 'Clinique Privée',
  },
  {
    name: 'Cabinet Médical Guynemer / Généralistes',
    category: 'sante',
    subtype: 'medecin',
    lat: 43.636,
    lon: 5.089,
    address: 'Avenue Georges Guynemer, 13300 Salon-de-Provence',
    badge: 'Médecins Généralistes',
  },

  // --- SPORTS, PARCS & LOISIRS ---
  {
    name: 'Stade & Complexe Sportif Saint-Côme',
    category: 'sport',
    subtype: 'terrain_sport',
    lat: 43.635,
    lon: 5.0862,
    address: '345 Rue Comte Devolx, 13300 Salon-de-Provence',
    badge: 'Stade & Athlétisme',
  },
  {
    name: 'Gymnase Municipal Saint-Côme',
    category: 'sport',
    subtype: 'gymnase',
    lat: 43.6352,
    lon: 5.0868,
    address: 'Avenue Georges Guynemer, 13300 Salon-de-Provence',
    badge: 'Gymnase & Sports Co',
  },
  {
    name: 'Centre Nautique Municipal / Piscine Olympique',
    category: 'sport',
    subtype: 'complexe_sportif',
    lat: 43.6392,
    lon: 5.1082,
    address: 'Avenue de Suisse, 13300 Salon-de-Provence',
    badge: 'Piscine Municipale',
  },
  {
    name: "Stade d'Honneur Marcel Roustan",
    category: 'sport',
    subtype: 'terrain_sport',
    lat: 43.643,
    lon: 5.1012,
    address: 'Boulevard David, 13300 Salon-de-Provence',
    badge: 'Stade Municipal',
  },
  {
    name: 'Tennis Club de Salon-de-Provence',
    category: 'sport',
    subtype: 'terrain_sport',
    lat: 43.6395,
    lon: 5.109,
    address: 'Avenue de Suisse, 13300 Salon-de-Provence',
    badge: 'Terrains Tennis & Padel',
  },
  {
    name: 'Parc Public de la Place Morgan',
    category: 'sport',
    subtype: 'parc',
    lat: 43.641,
    lon: 5.0935,
    address: 'Place Morgan, 13300 Salon-de-Provence',
    badge: 'Parc & Espace Détente',
  },
  {
    name: "Parc & Jardins du Château de l'Empéri",
    category: 'sport',
    subtype: 'parc',
    lat: 43.6422,
    lon: 5.0975,
    address: 'Montée du Puech, 13300 Salon-de-Provence',
    badge: 'Parc Historique',
  },

  // --- TRANSPORTS & MOBILITÉ ---
  {
    name: 'Arrêt de Bus Guynemer (Lignes Libébus 1, 3, 4)',
    category: 'transport',
    subtype: 'bus',
    lat: 43.636,
    lon: 5.0882,
    address: 'Avenue Georges Guynemer, 13300 Salon-de-Provence',
    badge: 'Réseau Libébus',
  },
  {
    name: 'Arrêt de Bus Saint-Côme (Lignes Libébus 1, 3)',
    category: 'transport',
    subtype: 'bus',
    lat: 43.6368,
    lon: 5.0872,
    address: 'Boulevard de la République, 13300 Salon-de-Provence',
    badge: 'Réseau Libébus',
  },
  {
    name: 'Gare SNCF de Salon-de-Provence (TER PACA)',
    category: 'transport',
    subtype: 'gare',
    lat: 43.6375,
    lon: 5.0965,
    address: 'Place de la Gare, 13300 Salon-de-Provence',
    badge: 'Gare TER (Marseille / Avignon / Miramas)',
  },
  {
    name: 'Gare Routière Pôle d’Échange Place Morgan',
    category: 'transport',
    subtype: 'bus',
    lat: 43.6402,
    lon: 5.0945,
    address: 'Place Morgan, 13300 Salon-de-Provence',
    badge: 'Lignes Cartreize / Zou & Libébus',
  },
];
