import type { StaticAmenityItem } from './amenities-data-salon';

export const PELISSANNE_AMENITIES: StaticAmenityItem[] = [
  // --- ÉDUCATION : COLLÈGE & ÉCOLES ---
  {
    name: 'Collège de Pélissanne',
    category: 'education',
    subtype: 'college',
    lat: 43.6338,
    lon: 5.1612,
    address: 'Route de Lambesc, 13330 Pélissanne',
    badge: 'Collège Public',
    phone: '04 90 55 08 50',
  },
  {
    name: 'École Primaire Jules Ferry',
    category: 'education',
    subtype: 'primaire',
    lat: 43.6315,
    lon: 5.1502,
    address: 'Avenue Saint-Roch, 13330 Pélissanne',
    badge: 'Primaire Publique',
  },
  {
    name: 'École Primaire Plan de Clavel',
    category: 'education',
    subtype: 'primaire',
    lat: 43.6292,
    lon: 5.1545,
    address: 'Rue de la République, 13330 Pélissanne',
    badge: 'Primaire Publique',
  },
  {
    name: 'École Maternelle Les Enjouvènes',
    category: 'education',
    subtype: 'maternelle',
    lat: 43.634,
    lon: 5.148,
    address: 'Avenue des Enjouvènes, 13330 Pélissanne',
    badge: 'Maternelle Publique',
  },
  {
    name: 'École Maternelle Le Clos',
    category: 'education',
    subtype: 'maternelle',
    lat: 43.6322,
    lon: 5.1538,
    address: 'Chemin du Clos, 13330 Pélissanne',
    badge: 'Maternelle Publique',
  },
  {
    name: 'École Élémentaire Jacques Prévert',
    category: 'education',
    subtype: 'primaire',
    lat: 43.6348,
    lon: 5.151,
    address: 'Avenue des Écoles, 13330 Pélissanne',
    badge: 'Primaire Publique',
  },

  // --- COMMERCES : SUPERMARCHÉS & SUPÉRETTES ---
  {
    name: 'Intermarché Contact Pélissanne',
    category: 'commerce',
    subtype: 'supermarche',
    lat: 43.6352,
    lon: 5.1458,
    address: 'Avenue des Enjouvènes, 13330 Pélissanne',
    badge: 'Supermarché & Station Service',
  },
  {
    name: 'Carrefour Contact Pélissanne',
    category: 'commerce',
    subtype: 'supermarche',
    lat: 43.6305,
    lon: 5.1395,
    address: 'Route de Salon, 13330 Pélissanne',
    badge: 'Supermarché Proximité',
  },
  {
    name: 'Supermarché Lidl Pélissanne',
    category: 'commerce',
    subtype: 'supermarche',
    lat: 43.6345,
    lon: 5.163,
    address: 'Route de Lambesc, 13330 Pélissanne',
    badge: 'Supermarché Discount',
  },
  {
    name: 'Supérette Utile Centre Village',
    category: 'commerce',
    subtype: 'superette',
    lat: 43.6318,
    lon: 5.1512,
    address: 'Place Pisavis, 13330 Pélissanne',
    badge: 'Alimentation Centre',
  },
  {
    name: 'Épicerie Vival Pélissanne',
    category: 'commerce',
    subtype: 'superette',
    lat: 43.6288,
    lon: 5.1495,
    address: 'Chemin des Oliviers, 13330 Pélissanne',
    badge: 'Supérette Proximité',
  },
  {
    name: 'Fournil des Enjouvènes',
    category: 'commerce',
    subtype: 'boulangerie',
    lat: 43.6348,
    lon: 5.1472,
    address: 'Avenue des Enjouvènes, 13330 Pélissanne',
    badge: 'Boulangerie Artisanale',
  },
  {
    name: 'Boulangerie de la Fontaine',
    category: 'commerce',
    subtype: 'boulangerie',
    lat: 43.6319,
    lon: 5.1518,
    address: 'Place de la Fontaine du Pélican, 13330 Pélissanne',
    badge: 'Boulangerie Centre',
  },
  {
    name: 'Marché Provençal de Pélissanne',
    category: 'commerce',
    subtype: 'marche',
    lat: 43.6316,
    lon: 5.151,
    address: 'Centre Ancien, 13330 Pélissanne',
    badge: 'Grand Marché Dimanche matin',
  },

  // --- SANTÉ & SOINS ---
  {
    name: 'Pharmacie des Enjouvènes',
    category: 'sante',
    subtype: 'pharmacie',
    lat: 43.6345,
    lon: 5.1465,
    address: 'Avenue des Enjouvènes, 13330 Pélissanne',
    badge: 'Pharmacie',
  },
  {
    name: 'Pharmacie Centrale Pélissanne',
    category: 'sante',
    subtype: 'pharmacie',
    lat: 43.6317,
    lon: 5.1508,
    address: 'Place Pisavis, 13330 Pélissanne',
    badge: 'Pharmacie',
  },
  {
    name: 'Pôle Médical des Oliviers / Généralistes',
    category: 'sante',
    subtype: 'medecin',
    lat: 43.6335,
    lon: 5.1585,
    address: 'Route de Lambesc, 13330 Pélissanne',
    badge: 'Maison Médicale',
  },

  // --- SPORTS & PARCS ---
  {
    name: 'Complexe Sportif de la Prouvenque',
    category: 'sport',
    subtype: 'complexe_sportif',
    lat: 43.6355,
    lon: 5.1625,
    address: 'Chemin de la Prouvenque, 13330 Pélissanne',
    badge: 'Stade, Tennis & Padel',
  },
  {
    name: 'Parc Saint-Roch & Aire de Loisirs',
    category: 'sport',
    subtype: 'parc',
    lat: 43.631,
    lon: 5.1485,
    address: 'Chemin Saint-Roch, 13330 Pélissanne',
    badge: 'Parc Ombragé & Jeux Enfants',
  },
  {
    name: 'City Stade & Skatepark de Pélissanne',
    category: 'sport',
    subtype: 'terrain_sport',
    lat: 43.635,
    lon: 5.161,
    address: 'Route de Lambesc, 13330 Pélissanne',
    badge: 'Sports Urbains',
  },

  // --- TRANSPORTS ---
  {
    name: 'Arrêt de Bus Enjouvènes (Ligne Libébus 8)',
    category: 'transport',
    subtype: 'bus',
    lat: 43.6342,
    lon: 5.1475,
    address: 'Avenue des Enjouvènes, 13330 Pélissanne',
    badge: 'Liaison directe Salon Centre',
  },
  {
    name: 'Arrêt de Bus Centre Village (Ligne 8 & Scolaires)',
    category: 'transport',
    subtype: 'bus',
    lat: 43.632,
    lon: 5.1505,
    address: 'Boulevard Victor Hugo, 13330 Pélissanne',
    badge: 'Réseau Libébus',
  },
];
