import { Buyer, MandateAuditLog, ContactLead, EstimationLead, TransactionDeal, ProspectingLead, AgencyKey, AgencySignboard, MandateAvenant, ProposalHistory, PartnerAgency, DelegationAgreement, ContactItem } from './types';

export const INITIAL_BUYERS: Buyer[] = [
  {
    id: 'buy-1',
    first_name: 'Alexandre',
    last_name: 'Moreau',
    email: 'a.moreau@example.com',
    phone: '06 12 34 56 78',
    status: 'actif',
    budget_max: 850000,
    min_surface: 140,
    min_rooms: 5,
    min_bedrooms: 4,
    target_property_types: ['maison'],
    target_cities: ['Salon-de-Provence', 'Pélissanne', 'Éguilles'],
    must_have_garden: true,
    must_have_garage: true,
    financing_status: 'accord_bancaire_valide',
    notes: 'Recherche active pour mutation. Coup de cœur pour les maisons récentes ou rénovées avec piscine.',
    created_at: '2024-02-10T10:00:00Z'
  },
  {
    id: 'buy-2',
    first_name: 'Céline & Thomas',
    last_name: 'Garnier',
    email: 'garnier.family@example.com',
    phone: '06 98 76 54 32',
    status: 'actif',
    budget_max: 580000,
    min_surface: 110,
    min_rooms: 4,
    min_bedrooms: 3,
    target_property_types: ['maison'],
    target_cities: ['Pélissanne', 'Lançon-Provence', 'La Fare-les-Oliviers'],
    must_have_garden: true,
    must_have_garage: false,
    financing_status: 'accord_bancaire_valide',
    notes: 'Famille avec 2 enfants. Proximité écoles et calme absolu requis.',
    created_at: '2024-02-15T14:30:00Z'
  },
  {
    id: 'buy-3',
    first_name: 'Marc',
    last_name: 'Vidal',
    email: 'm.vidal@invest.fr',
    phone: '06 45 67 89 01',
    status: 'actif',
    budget_max: 180000,
    min_surface: 25,
    min_rooms: 1,
    min_bedrooms: 1,
    target_property_types: ['appartement'],
    target_cities: ['Salon-de-Provence'],
    must_have_garden: false,
    must_have_garage: false,
    financing_status: 'comptant',
    notes: 'Investisseur locatif. Achat comptant sans condition suspensive de prêt.',
    created_at: '2024-03-01T09:15:00Z'
  },
  {
    id: 'buy-4',
    first_name: 'Sophie & Julien',
    last_name: 'Lambert',
    email: 'lambert.sophie@example.com',
    phone: '06 23 45 67 89',
    status: 'actif',
    budget_max: 470000,
    min_surface: 100,
    min_rooms: 4,
    min_bedrooms: 3,
    target_property_types: ['maison'],
    target_cities: ['Salon-de-Provence', 'Pélissanne'],
    must_have_garden: true,
    must_have_garage: true,
    financing_status: 'accord_bancaire_valide',
    notes: 'Recherche villa de plain-pied ou maison contemporaine récente.',
    created_at: '2024-03-05T16:00:00Z'
  },
  {
    id: 'buy-5',
    first_name: 'Laurent',
    last_name: 'Benoit',
    email: 'l.benoit@gmail.com',
    phone: '06 77 88 99 00',
    status: 'actif',
    budget_max: 300000,
    min_surface: 800,
    min_rooms: 0,
    min_bedrooms: 0,
    target_property_types: ['terrain'],
    target_cities: ['Pélissanne', 'Salon-de-Provence', 'Lançon-Provence'],
    must_have_garden: false,
    must_have_garage: false,
    financing_status: 'accord_bancaire_valide',
    notes: 'Recherche terrain à bâtir viabilisé avec permis ou libre constructeur.',
    created_at: '2024-03-10T11:20:00Z'
  }
];

export const INITIAL_AUDIT_LOGS: MandateAuditLog[] = [
  {
    id: 'log-1',
    property_id: 'prop-244',
    mandate_number: 244,
    action_type: 'creation',
    previous_state: null,
    new_state: {
      mandate_number: 244,
      title: 'SALON - LES VIOUGUES: 800m du CENTRE : Maison édifiée en 2023, 170m² Hab.',
      price_fai: 786600,
      status: 'actif'
    },
    performed_by: 'Nelly Fernandez',
    signature_sha256: 'a1b2c3d4e5f67890123456789abcdef0123456789abcdef0123456789abcdef0',
    logged_at: '2024-03-01T09:00:00Z'
  },
  {
    id: 'log-2',
    property_id: 'prop-243',
    mandate_number: 243,
    action_type: 'creation',
    previous_state: null,
    new_state: {
      mandate_number: 243,
      title: 'SALON 1km CENTRE: APPARTEMENT T1 - PARKING LIBRE FAIBLES CHARGES',
      price_fai: 95000,
      status: 'actif'
    },
    performed_by: 'Niels Fernandez',
    signature_sha256: 'b2c3d4e5f6a17890123456789abcdef0123456789abcdef0123456789abcdef0',
    logged_at: '2024-03-02T10:15:00Z'
  }
];

export { MOCK_DVF_TRANSACTIONS } from './mock-data-dvf';


export const INITIAL_CONTACT_LEADS: ContactLead[] = [
  {
    id: 'lead-1',
    name: 'Laurent Mercier',
    email: 'laurent.mercier@orange.fr',
    phone: '06 88 12 34 56',
    message: "Bonjour, je souhaiterais visiter la maison contemporaine aux Viougues (Réf 244) ce samedi si possible. Bien cordialement.",
    subject: "Demande de visite - Réf 244",
    property_id: 'prop-227',
    property_title: 'SALON - LES VIOUGUES: Maison contemporaine 170m²',
    status: 'nouveau',
    created_at: '2024-03-20T14:30:00Z'
  },
  {
    id: 'lead-2',
    name: 'Nathalie Bonnet',
    email: 'n.bonnet13@gmail.com',
    phone: '06 11 22 33 44',
    message: "Bonjour Nelly, nous avons vu la superbe maison de charme au centre de Pélissanne (Réf 235). Pourriez-vous nous transmettre le dossier complet et nous indiquer les disponibilités pour une visite ?",
    subject: "Demande d'information - Réf 235",
    property_id: 'prop-235',
    property_title: 'PÉLISSANNE CENTRE: Superbe Maison de charme 216m²',
    status: 'nouveau',
    created_at: '2024-03-21T09:15:00Z'
  }
];

export const INITIAL_ESTIMATION_LEADS: EstimationLead[] = [
  {
    id: 'est-1',
    first_name: 'Stéphane',
    last_name: 'Dumas',
    email: 's.dumas@bbox.fr',
    phone: '06 55 44 33 22',
    property_type: 'maison',
    city: 'Pélissanne',
    address: 'Chemin des Grands Prés',
    living_area: 145,
    land_area: 900,
    rooms_count: 5,
    has_pool: true,
    status: 'nouveau',
    created_at: '2024-03-19T17:40:00Z'
  },
  {
    id: 'est-2',
    first_name: 'Émilie',
    last_name: 'Roux',
    email: 'emilie.roux@sfr.fr',
    phone: '06 99 88 77 66',
    property_type: 'appartement',
    city: 'Salon-de-Provence',
    address: 'Place Morgan',
    living_area: 68,
    rooms_count: 3,
    has_pool: false,
    status: 'en_cours',
    created_at: '2024-03-18T11:00:00Z'
  }
];

export const INITIAL_TRANSACTIONS: TransactionDeal[] = [
  {
    id: 'trans-1',
    property_id: 'prop-227',
    buyer_id: 'buyer-1',
    status: 'attente_pret',
    offer_price_fai: 730000,
    offer_price_net: 700000,
    agency_fees_amount: 30000,
    deposit_amount: 35000,
    deposit_holder: 'Étude Notariale de Pélissanne (Me Bertrand)',
    seller_name: 'Jean-Pierre & Martine DUPONT',
    seller_phone: '06 12 34 56 78',
    seller_email: 'jp.dupont@orange.fr',
    buyer_name: 'Thomas & Sophie LEFEBVRE',
    buyer_phone: '06 88 77 66 55',
    buyer_email: 'thomas.lefebvre@gmail.com',
    seller_notary_name: 'Me Bertrand VIDAL',
    seller_notary_email: 'vidal.notaire@notaires.fr',
    seller_notary_phone: '04 90 55 12 34',
    seller_notary_office: 'Office Notarial de Pélissanne',
    buyer_notary_name: 'Me Caroline MARTIN',
    buyer_notary_email: 'c.martin@notaires.fr',
    buyer_notary_phone: '04 90 56 78 90',
    buyer_notary_office: 'Étude Notariale Salon République',
    offer_date: '2026-01-15',
    compromis_date: '2026-01-28',
    sru_notification_date: '2026-01-29',
    sru_expiry_date: '2026-02-09',
    loan_application_deadline: '2026-02-28',
    loan_approval_deadline: '2026-03-15',
    final_deed_target_date: '2026-04-10',
    loan_amount_requested: 550000,
    loan_interest_rate_max: 3.45,
    loan_duration_years: 25,
    loan_bank_name: 'BNP Paribas Salon-de-Provence',
    broker_name: 'Meilleurtaux Salon',
    checklist_documents: {
      titre_propriete: true,
      taxe_fonciere: true,
      dossier_diagnostics: true,
      audit_energetique: false,
      pre_etat_date: false,
      reglement_copro: false,
      cni_vendeur: true,
      cni_acquereur: true,
      justificatif_domicile: true,
      simulation_pret: true,
      offre_achat_signee: true
    },
    invoice_number: 'FACT-2026-004',
    invoice_date: '2026-04-10',
    invoice_sent_to_notary: false,
    fees_received: false,
    google_review_requested: false,
    notes: 'Alerte J-10 accord de prêt : relancer le courtier Meilleurtaux Salon pour confirmation de validation des offres.',
    created_at: '2026-01-15T10:00:00Z',
    updated_at: '2026-02-15T14:30:00Z'
  },
  {
    id: 'trans-2',
    property_id: 'prop-235',
    buyer_id: 'buyer-2',
    status: 'acte_planifie',
    offer_price_fai: 495000,
    offer_price_net: 475000,
    agency_fees_amount: 20000,
    deposit_amount: 25000,
    deposit_holder: 'Office Notarial de Salon',
    seller_name: 'Mme Valérie BLANCHARD',
    seller_phone: '06 23 45 67 89',
    seller_email: 'v.blanchard@sfr.fr',
    buyer_name: 'Julien & Camille MOREAU',
    buyer_phone: '06 34 56 78 90',
    buyer_email: 'julien.moreau@free.fr',
    seller_notary_name: 'Me Jean-Luc FAURE',
    seller_notary_email: 'faure.notaires@notaires.fr',
    seller_notary_phone: '04 90 56 11 22',
    seller_notary_office: 'Notaires Associés Place Morgan',
    offer_date: '2025-11-10',
    compromis_date: '2025-11-25',
    sru_notification_date: '2025-11-26',
    sru_expiry_date: '2025-12-08',
    loan_application_deadline: '2025-12-24',
    loan_approval_deadline: '2026-01-20',
    final_deed_target_date: '2026-03-12',
    loan_amount_requested: 380000,
    loan_interest_rate_max: 3.60,
    loan_duration_years: 20,
    loan_bank_name: 'Crédit Agricole Pélissanne',
    checklist_documents: {
      titre_propriete: true,
      taxe_fonciere: true,
      dossier_diagnostics: true,
      audit_energetique: true,
      pre_etat_date: false,
      reglement_copro: false,
      cni_vendeur: true,
      cni_acquereur: true,
      justificatif_domicile: true,
      simulation_pret: true,
      offre_achat_signee: true
    },
    invoice_number: 'FACT-2026-003',
    invoice_date: '2026-03-05',
    invoice_sent_to_notary: true,
    fees_received: false,
    google_review_requested: false,
    notes: 'Signature fixée le 12 mars à 15h00. Relecture du projet d’acte effectuée avec Me Faure.',
    created_at: '2025-11-10T14:00:00Z',
    updated_at: '2026-02-20T11:00:00Z'
  },
  {
    id: 'trans-3',
    property_id: 'prop-243',
    status: 'acte_signe',
    offer_price_fai: 95000,
    offer_price_net: 89000,
    agency_fees_amount: 6000,
    deposit_amount: 5000,
    deposit_holder: 'Me Bertrand VIDAL (Pélissanne)',
    seller_name: 'M. Henri GIRAUD',
    seller_phone: '06 99 88 11 22',
    seller_email: 'henri.giraud@wanadoo.fr',
    buyer_name: 'Romain BOURGEOIS (Investisseur)',
    buyer_phone: '06 77 66 55 44',
    buyer_email: 'romain.bourgeois@gmail.com',
    seller_notary_name: 'Me Bertrand VIDAL',
    seller_notary_email: 'vidal.notaire@notaires.fr',
    seller_notary_phone: '04 90 55 12 34',
    seller_notary_office: 'Office Notarial de Pélissanne',
    offer_date: '2025-10-01',
    compromis_date: '2025-10-18',
    sru_notification_date: '2025-10-19',
    sru_expiry_date: '2025-10-30',
    loan_application_deadline: '2025-11-20',
    loan_approval_deadline: '2025-12-15',
    final_deed_target_date: '2026-01-22',
    actual_closing_date: '2026-01-22',
    checklist_documents: {
      titre_propriete: true,
      taxe_fonciere: true,
      dossier_diagnostics: true,
      audit_energetique: false,
      pre_etat_date: true,
      reglement_copro: true,
      cni_vendeur: true,
      cni_acquereur: true,
      justificatif_domicile: true,
      simulation_pret: true,
      offre_achat_signee: true
    },
    invoice_number: 'FACT-2026-001',
    invoice_date: '2026-01-22',
    invoice_sent_to_notary: true,
    fees_received: true,
    google_review_requested: true,
    notes: 'Acte signé le 22/01. Honoraires de 6 000 € encaissés le 24/01. Avis 5 étoiles Google reçu !',
    created_at: '2025-10-01T09:30:00Z',
    updated_at: '2026-01-25T16:00:00Z'
  }
];

export const INITIAL_PROSPECTING_LEADS: ProspectingLead[] = [
  {
    id: 'pige-1',
    source: 'pap',
    source_url: 'https://www.pap.fr/annonces/maison-pelissanne-13330-r44120',
    title: 'Villa provençale 135m² sur 950m² de terrain arboré avec piscine',
    property_type: 'maison',
    city: 'Pélissanne',
    postal_code: '13330',
    price_asked: 460000,
    initial_price: 495000,
    price_drops_count: 1,
    living_area: 135,
    land_area: 950,
    rooms_count: 5,
    bedrooms_count: 3,
    description: 'Particulier vend villa traditionnelle de plain-pied, quartier calme à 1,5km du centre. Séjour lumineux de 42m² avec cheminée, cuisine équipée indépendante, 3 chambres, garage, piscine 8x4m avec terrasse ombragée. Agences s\'abstenir impérativement.',
    photos_urls: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80'
    ],
    seller_name: 'M. Jean-Luc DUBOIS',
    seller_phone: '06 14 25 36 47',
    seller_email: 'jeanluc.dubois13@gmail.com',
    status: 'a_rappeler',
    call_attempts_count: 2,
    last_contacted_at: '2026-02-28T14:30:00Z',
    next_followup_date: '2026-03-05',
    notes: 'Premier contact le 28/02. A d\'abord refusé par principe, mais a reconnu que depuis sa baisse de 35 000€ il n\'a eu que 2 visites non finançables. D\'accord pour que je lui prépare une estimation comparative DVF de sa rue.',
    estimated_dvf_m2: 3250,
    estimated_dvf_price: 438000,
    days_online: 82,
    created_at: '2025-12-10T10:00:00Z'
  },
  {
    id: 'pige-2',
    source: 'leboncoin',
    source_url: 'https://www.leboncoin.fr/ad/ventes_immobilieres/298412450.htm',
    title: 'Maison contemporaine rénovée 110m² - Quartier Viougues',
    property_type: 'maison',
    city: 'Salon-de-Provence',
    postal_code: '13300',
    price_asked: 365000,
    price_drops_count: 0,
    living_area: 110,
    land_area: 380,
    rooms_count: 4,
    bedrooms_count: 3,
    description: 'En direct propriétaire : maison coup de cœur entièrement rénovée avec goût en 2024. Climatisation réversible, suite parentale en rez-de-chaussée, jardin sans vis-à-vis. DPE classe B.',
    photos_urls: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80'
    ],
    seller_name: 'Mme Sophie ROUX',
    seller_phone: '06 88 77 44 11',
    seller_email: 'sophie.roux.salon@gmail.com',
    status: 'nouveau',
    call_attempts_count: 0,
    notes: 'Annonce mise en ligne il y a 36 heures. Quartier très recherché par nos acquéreurs famille (budget 350-380k€). Appel prioritaire à passer avec le script d\'accroche Nell\'Immo.',
    estimated_dvf_m2: 3280,
    estimated_dvf_price: 360000,
    days_online: 2,
    created_at: '2026-03-01T08:00:00Z'
  },
  {
    id: 'pige-3',
    source: 'pap',
    source_url: 'https://www.pap.fr/annonces/maison-lambesc-13410-r44199',
    title: 'Propriété de charme avec dépendance et oliveraie 180m²',
    property_type: 'maison',
    city: 'Lambesc',
    postal_code: '13410',
    price_asked: 675000,
    initial_price: 720000,
    price_drops_count: 1,
    living_area: 180,
    land_area: 2500,
    rooms_count: 7,
    bedrooms_count: 4,
    description: 'Vends superbe mas rénové sur terrain de 2500m² avec 30 oliviers centenaires. Grande terrasse, vue sur les collines, piscine chauffée. Pas d\'agences merci.',
    photos_urls: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80'
    ],
    seller_name: 'Dr. Marc BENOIT',
    seller_phone: '06 50 60 70 80',
    seller_email: 'marc.benoit.med@gmail.com',
    status: 'rdv_pris',
    call_attempts_count: 3,
    last_contacted_at: '2026-03-01T17:00:00Z',
    next_followup_date: '2026-03-06',
    notes: 'RDV d\'estimation fixé le vendredi 6 mars à 14h30. Les propriétaires déménagent en région lyonnaise et sont fatigués de gérer les curieux le week-end.',
    estimated_dvf_m2: 3600,
    estimated_dvf_price: 648000,
    days_online: 74,
    created_at: '2025-12-18T11:00:00Z'
  },
  {
    id: 'pige-4',
    source: 'boitage',
    title: 'Maison traditionnelle quartier Les Costes - Contact Boîtage',
    property_type: 'maison',
    city: 'Pélissanne',
    postal_code: '13330',
    price_asked: 410000,
    price_drops_count: 0,
    living_area: 120,
    land_area: 600,
    rooms_count: 5,
    bedrooms_count: 3,
    description: 'Propriétaire ayant contacté l\'agence suite au flyer déposé dans sa boîte aux lettres. Projet de vente pour départ en retraite d\'ici fin 2026.',
    photos_urls: [],
    seller_name: 'M. et Mme ROUSTAN',
    seller_phone: '04 90 55 89 22',
    status: 'nouveau',
    call_attempts_count: 1,
    last_contacted_at: '2026-02-27T10:00:00Z',
    next_followup_date: '2026-03-04',
    notes: 'Très bon accueil au téléphone. Préfèrent confier l\'exclusivité à une agence locale de Pélissanne plutôt qu\'à un grand réseau national.',
    estimated_dvf_m2: 3300,
    estimated_dvf_price: 396000,
    days_online: 5,
    created_at: '2026-02-25T14:00:00Z'
  }
];

export const INITIAL_AGENCY_KEYS: AgencyKey[] = [
  {
    id: 'key-1',
    property_id: 'prop-227',
    keyring_number: 244,
    cabinet_location: 'Armoire A • Rgt 01',
    keys_count: 3,
    has_alarm_badge: true,
    status: 'disponible',
    notes: 'Trousseau complet : Portail coulissant, porte entrée sécurité 5 points, porte de garage motorisé + badge Vigik alarme.',
    created_at: '2025-10-06T09:00:00Z'
  },
  {
    id: 'key-2',
    property_id: 'prop-228',
    keyring_number: 228,
    cabinet_location: 'Armoire A • Rgt 02',
    keys_count: 2,
    has_alarm_badge: false,
    status: 'prete',
    current_borrower: {
      id: 'loan-1',
      key_id: 'key-2',
      borrower_name: 'Jean-Luc Morvan',
      borrower_phone: '06 12 34 56 78',
      borrower_company: 'DiagMéditerranée SAS',
      borrower_role: 'diagnostiqueur',
      borrowed_at: new Date(Date.now() - 3600000 * 24).toISOString(),
      expected_return_at: new Date(Date.now() + 3600000 * 6).toISOString(),
      purpose: 'Réalisation du métrage Loi Carrez et mise à jour de l\'audit énergétique',
      discharged: true
    },
    loan_history: [
      {
        id: 'loan-1',
        key_id: 'key-2',
        borrower_name: 'Jean-Luc Morvan',
        borrower_phone: '06 12 34 56 78',
        borrower_company: 'DiagMéditerranée SAS',
        borrower_role: 'diagnostiqueur',
        borrowed_at: new Date(Date.now() - 3600000 * 24).toISOString(),
        expected_return_at: new Date(Date.now() + 3600000 * 6).toISOString(),
        purpose: 'Réalisation du métrage Loi Carrez et mise à jour de l\'audit énergétique',
        discharged: true
      }
    ],
    notes: 'Prêt en cours au diagnostiqueur agréé.',
    created_at: '2025-09-12T10:00:00Z'
  },
  {
    id: 'key-3',
    property_id: 'prop-229',
    keyring_number: 229,
    cabinet_location: 'Armoire B • Rgt 05',
    keys_count: 4,
    has_alarm_badge: true,
    status: 'disponible',
    notes: 'Clés maison de village Lambesc (Porte principale, cave voûtée, atelier jardin).',
    created_at: '2025-11-04T11:30:00Z'
  },
  {
    id: 'key-4',
    property_id: 'prop-230',
    keyring_number: 230,
    cabinet_location: 'Armoire B • Rgt 06',
    keys_count: 1,
    has_alarm_badge: false,
    status: 'double_proprietaire',
    notes: 'Le propriétaire réside sur place, double de secours d\'agence pour visites accompagnées.',
    created_at: '2026-01-08T14:15:00Z'
  }
];

export const INITIAL_AGENCY_SIGNBOARDS: AgencySignboard[] = [
  {
    id: 'sign-1',
    property_id: 'prop-227',
    signboard_type: 'exclusivite',
    status: 'pose',
    installed_at: '2025-10-10',
    location_details: 'Portail d\'entrée sur voie publique, Les Viougues, Salon-de-Provence',
    notes: 'Panneau Akilux 80x60 cm avec œillets et colliers de serrage renforcés.',
    created_at: '2025-10-10T10:00:00Z'
  },
  {
    id: 'sign-2',
    property_id: 'prop-228',
    signboard_type: 'vendu',
    status: 'a_deposer',
    installed_at: '2025-11-15',
    removal_deadline: new Date(Date.now() + 3600000 * 24 * 4).toISOString().slice(0, 10),
    location_details: 'Clôture sur avenue principale, Pélissanne',
    notes: 'Réglementation Loi Grenelle II : dépose obligatoire sous 3 mois après la signature de l\'acte authentique.',
    created_at: '2025-11-15T09:00:00Z'
  },
  {
    id: 'sign-3',
    property_id: 'prop-229',
    signboard_type: 'a_vendre',
    status: 'pose',
    installed_at: '2026-01-18',
    location_details: 'Façade sur rue commerçante, Lambesc',
    notes: 'Panneau en V pour double visibilité piétonne et routière.',
    created_at: '2026-01-18T14:00:00Z'
  },
  {
    id: 'sign-4',
    signboard_type: 'a_vendre',
    status: 'en_stock',
    location_details: 'Réserve Agence Nell\'Immo',
    notes: 'Panneau neuf prêt pour nouveau mandat exclusif.',
    created_at: '2026-02-01T08:00:00Z'
  },
  {
    id: 'sign-5',
    signboard_type: 'vendu',
    status: 'en_stock',
    location_details: 'Réserve Agence Nell\'Immo',
    notes: 'Panneau VENDU réutilisable en parfait état.',
    created_at: '2026-02-01T08:00:00Z'
  }
];

export const INITIAL_MANDATE_AVENANTS: MandateAvenant[] = [
  {
    id: 'avenant-1',
    mandate_number: 244,
    property_id: 'prop-227',
    avenant_number: 1,
    avenant_type: 'baisse_prix',
    previous_price_fai: 815000,
    new_price_fai: 786600,
    previous_price_net: 782400,
    new_price_net: 755136,
    previous_fees_amount: 32600,
    new_fees_amount: 31464,
    reason: 'Repositionnement tarifaire après 4 visites qualifiées pour dynamiser les offres avant le printemps.',
    effective_date: '2025-11-20',
    is_signed: true,
    signed_at: '2025-11-20T14:30:00Z',
    signature_sha256: '9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f8e',
    created_at: '2025-11-20T14:00:00Z'
  }
];

export const INITIAL_PROPOSALS: ProposalHistory[] = [
  {
    id: 'prop-hist-1',
    property_id: 'prop-227',
    buyer_id: 'buyer-1',
    proposed_at: '2026-02-15T10:00:00Z',
    channel: 'whatsapp',
    status: 'interesse',
    feedback: 'Très enthousiaste sur la pièce de vie de 65m² et la piscine. Visite programmée avec succès.'
  },
  {
    id: 'prop-hist-2',
    property_id: 'prop-227',
    buyer_id: 'buyer-2',
    proposed_at: '2026-02-18T15:30:00Z',
    channel: 'email',
    status: 'refuse',
    feedback: 'Recherche une parcelle plus vaste (> 1 000 m²) pour chevaux.'
  }
];

export const INITIAL_PARTNERS: PartnerAgency[] = [
  {
    id: 'part-1',
    agency_name: 'Agence Provençale de Salon',
    director_name: 'Jean-Marc Bertrand',
    cpi_number: 'CPI 1310 2021 000 012 345',
    city: 'Salon-de-Provence',
    phone: '04 90 56 12 34',
    email: 'contact@agenceprovencale-salon.fr',
    financial_guarantee: 'Galian (140 000 €)'
  },
  {
    id: 'part-2',
    agency_name: 'Immobilier du Pays d\'Aix & Luberon',
    director_name: 'Stéphanie Martin',
    cpi_number: 'CPI 1310 2018 000 034 567',
    city: 'Aix-en-Provence',
    phone: '04 42 20 55 66',
    email: 'direction@immo-paysdaix.com',
    financial_guarantee: 'SNPI (120 000 €)'
  },
  {
    id: 'part-3',
    agency_name: 'Lambesc Prestige & Propriétés',
    director_name: 'Laurent Mercier',
    cpi_number: 'CPI 1310 2020 000 023 890',
    city: 'Lambesc',
    phone: '04 42 92 88 10',
    email: 'contact@lambesc-prestige.fr',
    financial_guarantee: 'QBE Europe (120 000 €)'
  }
];

export const INITIAL_DELEGATIONS: DelegationAgreement[] = [
  {
    id: 'del-101',
    property_id: 'prop-227',
    partner_id: 'part-1',
    fee_share_ratio: '50_50',
    delegation_type: 'co_exclusivite',
    start_date: '2026-02-01',
    end_date: '2026-05-01',
    status: 'active',
    special_clauses: 'Visites accompagnées obligatoires par Nell\'Immo lors des 2 premières semaines.'
  }
];

export const INITIAL_CONTACTS: ContactItem[] = [
  // NOTAIRES
  {
    id: 'cont-not-1',
    role: 'notaire',
    status: 'vip',
    civility: 'M',
    first_name: 'Jean-Luc',
    last_name: 'Faure',
    company: 'Office Notarial Morgan & Associés',
    specialty: 'Notaire associé — Ventes & Successions',
    email: 'faure.notaires@notaires.fr',
    secondary_email: 'clerc.faure@notaires.fr',
    phone: '04 90 56 11 22',
    secondary_phone: '06 11 22 33 44',
    address: '14 Place Morgan',
    postal_code: '13300',
    city: 'Salon-de-Provence',
    website: 'https://notaires-salon-faure.fr',
    siret: '381 294 812 00019',
    associated_property_ids: ['prop-235'],
    is_favorite: true,
    tags: ['Notaire Référent', 'Réactif', 'Actes Rapides'],
    notes: 'Office notarial principal de Nell\'Immo sur Salon. Rédaction des compromis en moins de 8 jours ouvrés si dossier ALUR complet. Clerc référent : Mme Sylvie Bertrand.',
    interactions: [
      {
        id: 'inter-1',
        contact_id: 'cont-not-1',
        type: 'email_gmail',
        title: 'Transmission projet d’acte authentique',
        description: 'Envoi du décompte acquéreur et confirmation de la date du 12 mars pour le mandat 235.',
        date: '2026-02-28T14:30:00Z',
        author: 'Nelly'
      },
      {
        id: 'inter-2',
        contact_id: 'cont-not-1',
        type: 'appel',
        title: 'Point d’étape sur la purge SRU',
        description: 'Confirmation de réception de l’avis de passage AR sans rétractation.',
        date: '2026-02-15T11:00:00Z',
        author: 'Nelly'
      }
    ],
    created_at: '2024-01-10T09:00:00Z',
    updated_at: '2026-02-28T14:30:00Z',
    last_contact_at: '2026-02-28T14:30:00Z'
  },
  {
    id: 'cont-not-2',
    role: 'notaire',
    status: 'actif',
    civility: 'M',
    first_name: 'Bertrand',
    last_name: 'Vidal',
    company: 'Étude Notariale des Oliviers',
    specialty: 'Notaire titulaire — Droit immobilier',
    email: 'b.vidal@notaires.fr',
    phone: '04 90 55 02 18',
    address: '8 Boulevard Carnot',
    postal_code: '13330',
    city: 'Pélissanne',
    siret: '419 832 901 00028',
    associated_property_ids: ['prop-243', 'prop-227'],
    is_favorite: true,
    tags: ['Notaire Pélissanne', 'Foncier & Terrain'],
    notes: 'Très bonne connaissance du cadastre et des servitudes sur Pélissanne et La Barben.',
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2026-02-20T16:00:00Z',
    last_contact_at: '2026-02-20T16:00:00Z'
  },
  {
    id: 'cont-not-3',
    role: 'notaire',
    status: 'actif',
    civility: 'Mme',
    first_name: 'Claire',
    last_name: 'Giraud',
    company: 'Giraud & Associés Notaires',
    specialty: 'Notaire associée — Patrimoine & Démembrement',
    email: 'c.giraud@notaires.fr',
    phone: '04 42 27 89 00',
    address: '22 Cours Mirabeau',
    postal_code: '13100',
    city: 'Aix-en-Provence',
    is_favorite: false,
    tags: ['Aix-en-Provence', 'Prestige'],
    notes: 'Intervient sur les dossiers de belles propriétés et successions complexes.',
    created_at: '2024-03-01T14:00:00Z',
    updated_at: '2026-01-25T11:00:00Z',
    last_contact_at: '2026-01-25T11:00:00Z'
  },

  // DIAGNOSTIQUEURS
  {
    id: 'cont-diag-1',
    role: 'diagnostiqueur',
    status: 'vip',
    civility: 'M',
    first_name: 'Stéphane',
    last_name: 'Fabre',
    company: 'SAS Diag Provence ALUR',
    specialty: 'Diagnostiqueur certifié avec mention & Auditeur énergétique',
    email: 'contact@diag-provence-alur.fr',
    phone: '06 42 10 98 76',
    secondary_phone: '04 90 55 43 21',
    address: 'Zone Artisanale Les Roquassiers',
    postal_code: '13300',
    city: 'Salon-de-Provence',
    website: 'https://diag-provence-alur.fr',
    siret: '802 918 334 00012',
    associated_property_ids: ['prop-227', 'prop-235'],
    is_favorite: true,
    tags: ['Partenaire Prioritaire', 'Audit Énergétique', 'Rapports 48h'],
    notes: 'Remise des rapports en 48h chrono. Tarifs négociés agence Nell\'Immo (-15% sur les packs complets). Clés disponibles à l\'agence.',
    interactions: [
      {
        id: 'inter-3',
        contact_id: 'cont-diag-1',
        type: 'email_gmail',
        title: 'Ordre de mission Audit Énergétique',
        description: 'Mission pour la villa à Pélissanne suite au nouveau DPE.',
        date: '2026-02-18T09:15:00Z',
        author: 'Nelly'
      }
    ],
    created_at: '2024-01-12T08:00:00Z',
    updated_at: '2026-02-18T09:15:00Z',
    last_contact_at: '2026-02-18T09:15:00Z'
  },
  {
    id: 'cont-diag-2',
    role: 'diagnostiqueur',
    status: 'actif',
    civility: 'M',
    first_name: 'Thierry',
    last_name: 'Mercier',
    company: 'Diag Sud Expertise',
    specialty: 'DDT, Loi Carrez, Amiante avant-travaux',
    email: 't.mercier@diagsud-expertise.com',
    phone: '06 18 29 40 51',
    address: '5 Avenue de la République',
    postal_code: '13330',
    city: 'Pélissanne',
    is_favorite: false,
    tags: ['Pélissanne', 'Réactif'],
    notes: 'Disponible le samedi matin si urgence pour mise en vente rapide.',
    created_at: '2024-04-10T10:00:00Z',
    updated_at: '2026-01-14T15:00:00Z',
    last_contact_at: '2026-01-14T15:00:00Z'
  },

  // COURTIERS & BANQUES
  {
    id: 'cont-court-1',
    role: 'courtier',
    status: 'vip',
    civility: 'Mme',
    first_name: 'Sandrine',
    last_name: 'Blanc',
    company: 'Meilleurtaux Salon-de-Provence',
    specialty: 'Directrice d\'agence — Financement de prêt immobilier',
    email: 'sblanc@meilleurtaux.com',
    phone: '06 77 88 99 00',
    secondary_phone: '04 90 56 70 80',
    address: '42 Cours Victor Hugo',
    postal_code: '13300',
    city: 'Salon-de-Provence',
    website: 'https://meilleurtaux.com/salon',
    siret: '512 889 001 00034',
    is_favorite: true,
    tags: ['Partenaire Financement', 'Attestations < 24h'],
    notes: 'Établit des attestations de confort financier très fiables avant de faire signer une offre d\'achat aux vendeurs.',
    interactions: [
      {
        id: 'inter-4',
        contact_id: 'cont-court-1',
        type: 'appel',
        title: 'Validation dossier acquéreur Garnier',
        description: 'Accord de principe obtenu avec la Caisse d’Épargne à 3.45% sur 25 ans.',
        date: '2026-03-01T17:00:00Z',
        author: 'Nelly'
      }
    ],
    created_at: '2024-01-20T11:00:00Z',
    updated_at: '2026-03-01T17:00:00Z',
    last_contact_at: '2026-03-01T17:00:00Z'
  },
  {
    id: 'cont-court-2',
    role: 'courtier',
    status: 'actif',
    civility: 'M',
    first_name: 'François',
    last_name: 'Roussel',
    company: 'Crédit Agricole Alpes Provence',
    specialty: 'Directeur d\'agence bancaire',
    email: 'francois.roussel@ca-alpesprovence.fr',
    phone: '04 90 55 12 34',
    address: 'Place Roux de Brignoles',
    postal_code: '13330',
    city: 'Pélissanne',
    is_favorite: false,
    tags: ['Banque Locale', 'Pélissanne'],
    notes: 'Interlocuteur direct pour les prêts immobiliers des résidents de Pélissanne et Aurons.',
    created_at: '2024-02-15T09:00:00Z',
    updated_at: '2026-02-10T14:00:00Z',
    last_contact_at: '2026-02-10T14:00:00Z'
  },

  // ARTISANS & BTP
  {
    id: 'cont-art-1',
    role: 'artisan',
    status: 'vip',
    civility: 'M',
    first_name: 'Pierre',
    last_name: 'Vasseur',
    company: 'SAS Provence Rénov BTP',
    specialty: 'Rénovation générale, Maçonnerie & Climatisation',
    email: 'contact@provence-renov-btp.fr',
    phone: '06 50 60 70 80',
    secondary_phone: '04 90 53 10 20',
    address: 'Chemin de la Crau',
    postal_code: '13300',
    city: 'Salon-de-Provence',
    siret: '791 445 667 00021',
    is_favorite: true,
    tags: ['Rénovation Complète', 'Garantie Décennale', 'Devis Rapide'],
    notes: 'Assurance décennale AXA à jour (copie disponible dans le dossier). Réalise des chiffrages avant-achat pour nos acquéreurs.',
    created_at: '2024-02-01T14:00:00Z',
    updated_at: '2026-02-25T10:00:00Z',
    last_contact_at: '2026-02-25T10:00:00Z'
  },
  {
    id: 'cont-art-2',
    role: 'artisan',
    status: 'actif',
    civility: 'M',
    first_name: 'David',
    last_name: 'Blanc',
    company: 'Électricité Générale du Pays Salonais',
    specialty: 'Électricien — Remise aux normes & Tableaux DPE',
    email: 'd.blanc.elec@orange.fr',
    phone: '06 33 44 55 66',
    address: '12 Impasse des Lavandes',
    postal_code: '13330',
    city: 'Pélissanne',
    is_favorite: false,
    tags: ['Électricité', 'Remise aux Normes'],
    notes: 'Intervient souvent pour lever les anomalies électriques constatées lors des diagnostics de vente.',
    created_at: '2024-03-10T16:00:00Z',
    updated_at: '2026-01-18T11:00:00Z',
    last_contact_at: '2026-01-18T11:00:00Z'
  },

  // SYNDICS & GÉOMÈTRES
  {
    id: 'cont-syn-1',
    role: 'syndic',
    status: 'actif',
    civility: 'Mme',
    first_name: 'Élodie',
    last_name: 'Brun',
    company: 'Cabinet Syndic Provence Gestion',
    specialty: 'Gestionnaire de Copropriétés',
    email: 'e.brun@syndic-provence-gestion.com',
    phone: '04 90 56 88 99',
    address: '28 Boulevard Foch',
    postal_code: '13300',
    city: 'Salon-de-Provence',
    siret: '448 901 234 00018',
    is_favorite: false,
    tags: ['Syndic Copro', 'Pré-état Daté'],
    notes: 'Gestionnaire des résidences Le Clos des Oliviers et Les Jardins de Pélissanne. Délais pré-état daté : ~10 jours ouvrés.',
    created_at: '2024-02-20T10:00:00Z',
    updated_at: '2026-01-30T14:00:00Z',
    last_contact_at: '2026-01-30T14:00:00Z'
  },

  // VENDEURS
  {
    id: 'cont-vend-1',
    role: 'vendeur',
    status: 'actif',
    civility: 'Mme',
    first_name: 'Valérie',
    last_name: 'Blanchard',
    company: 'Propriétaire particulier',
    specialty: 'Vendeur Mandat Exclusif #235',
    email: 'v.blanchard@sfr.fr',
    phone: '06 23 45 67 89',
    address: '15 Chemin des Enjouvènes',
    postal_code: '13330',
    city: 'Pélissanne',
    associated_property_ids: ['prop-235'],
    is_favorite: true,
    tags: ['Vendeur Exclusif', 'Sous Compromis'],
    notes: 'Vente villa contemporaine 495 000 €. Signature acte authentique programmée le 12 mars chez Me Faure.',
    created_at: '2025-10-15T09:00:00Z',
    updated_at: '2026-02-28T16:00:00Z',
    last_contact_at: '2026-02-28T16:00:00Z'
  },

  // ACQUÉREURS
  {
    id: 'cont-acq-1',
    role: 'acquereur',
    status: 'vip',
    civility: 'M',
    first_name: 'Alexandre',
    last_name: 'Moreau',
    company: 'Particulier',
    specialty: 'Acquéreur qualifié — Budget 850 k€',
    email: 'a.moreau@example.com',
    phone: '06 12 34 56 78',
    address: 'Résidence actuelle Aix-en-Provence',
    postal_code: '13100',
    city: 'Aix-en-Provence',
    is_favorite: true,
    tags: ['Budget VIP', 'Financement Validé', 'Recherche Villa'],
    notes: 'Recherche villa contemporaine 140 m²+ avec piscine sur Salon, Pélissanne ou Éguilles. Mutation professionnelle prévue cet été.',
    created_at: '2024-02-10T10:00:00Z',
    updated_at: '2026-02-26T15:00:00Z',
    last_contact_at: '2026-02-26T15:00:00Z'
  },

  // CONFRÈRES & PARTENAIRES
  {
    id: 'cont-conf-1',
    role: 'confrere',
    status: 'actif',
    civility: 'M',
    first_name: 'Alain',
    last_name: 'Bonnet',
    company: 'Agence Salon Centre Immobilier',
    specialty: 'Directeur d\'agence — Bourse Inter-Agences',
    email: 'contact@salon-centre-immo.fr',
    phone: '04 90 56 00 11',
    address: '10 Cours Gimon',
    postal_code: '13300',
    city: 'Salon-de-Provence',
    is_favorite: false,
    tags: ['Inter-Agences', 'Délégation Mandat'],
    notes: 'Partenaire conventionné pour délégation de mandats partagés (partage d\'honoraires 50/50).',
    created_at: '2024-01-25T11:00:00Z',
    updated_at: '2026-02-12T10:00:00Z',
    last_contact_at: '2026-02-12T10:00:00Z'
  }
];

