import { Property, Buyer, VisitSheet, MandateAuditLog, AgencySettings, DVFTransaction, ContactLead, EstimationLead, TransactionDeal, ProspectingLead, VendorReport, AgencyKey, AgencySignboard, MandateAvenant, ProposalHistory } from './types';

export const INITIAL_BUYERS: Buyer[] = [
  {
    id: 'buy-1',
    first_name: 'Alexandre',
    last_name: 'Moreau',
    email: 'a.moreau@example.com',
    phone: '06 12 34 56 78',
    status: 'actif',
    budget_max: 850000,
    min_surface: 140,
    min_rooms: 5,
    min_bedrooms: 4,
    target_property_types: ['maison'],
    target_cities: ['Salon-de-Provence', 'Pélissanne', 'Éguilles'],
    must_have_garden: true,
    must_have_garage: true,
    financing_status: 'accord_bancaire_valide',
    notes: 'Recherche active pour mutation. Coup de cœur pour les maisons récentes ou rénovées avec piscine.',
    created_at: '2024-02-10T10:00:00Z'
  },
  {
    id: 'buy-2',
    first_name: 'Céline & Thomas',
    last_name: 'Garnier',
    email: 'garnier.family@example.com',
    phone: '06 98 76 54 32',
    status: 'actif',
    budget_max: 580000,
    min_surface: 110,
    min_rooms: 4,
    min_bedrooms: 3,
    target_property_types: ['maison'],
    target_cities: ['Pélissanne', 'Lançon-Provence', 'La Fare-les-Oliviers'],
    must_have_garden: true,
    must_have_garage: false,
    financing_status: 'accord_bancaire_valide',
    notes: 'Famille avec 2 enfants. Proximité écoles et calme absolu requis.',
    created_at: '2024-02-15T14:30:00Z'
  },
  {
    id: 'buy-3',
    first_name: 'Marc',
    last_name: 'Vidal',
    email: 'm.vidal@invest.fr',
    phone: '06 45 67 89 01',
    status: 'actif',
    budget_max: 180000,
    min_surface: 25,
    min_rooms: 1,
    min_bedrooms: 1,
    target_property_types: ['appartement'],
    target_cities: ['Salon-de-Provence'],
    must_have_garden: false,
    must_have_garage: false,
    financing_status: 'comptant',
    notes: 'Investisseur locatif. Achat comptant sans condition suspensive de prêt.',
    created_at: '2024-03-01T09:15:00Z'
  },
  {
    id: 'buy-4',
    first_name: 'Sophie & Julien',
    last_name: 'Lambert',
    email: 'lambert.sophie@example.com',
    phone: '06 23 45 67 89',
    status: 'actif',
    budget_max: 470000,
    min_surface: 100,
    min_rooms: 4,
    min_bedrooms: 3,
    target_property_types: ['maison'],
    target_cities: ['Salon-de-Provence', 'Pélissanne'],
    must_have_garden: true,
    must_have_garage: true,
    financing_status: 'accord_bancaire_valide',
    notes: 'Recherche villa de plain-pied ou maison contemporaine récente.',
    created_at: '2024-03-05T16:00:00Z'
  },
  {
    id: 'buy-5',
    first_name: 'Laurent',
    last_name: 'Benoit',
    email: 'l.benoit@gmail.com',
    phone: '06 77 88 99 00',
    status: 'actif',
    budget_max: 300000,
    min_surface: 800,
    min_rooms: 0,
    min_bedrooms: 0,
    target_property_types: ['terrain'],
    target_cities: ['Pélissanne', 'Salon-de-Provence', 'Lançon-Provence'],
    must_have_garden: false,
    must_have_garage: false,
    financing_status: 'accord_bancaire_valide',
    notes: 'Recherche terrain à bâtir viabilisé avec permis ou libre constructeur.',
    created_at: '2024-03-10T11:20:00Z'
  }
];

export const INITIAL_AUDIT_LOGS: MandateAuditLog[] = [
  {
    id: 'log-1',
    property_id: 'prop-244',
    mandate_number: 244,
    action_type: 'creation',
    previous_state: null,
    new_state: {
      mandate_number: 244,
      title: 'SALON - LES VIOUGUES: 800m du CENTRE : Maison édifiée en 2023, 170m² Hab.',
      price_fai: 786600,
      status: 'actif'
    },
    performed_by: 'Nelly Fernandez',
    signature_sha256: 'a1b2c3d4e5f67890123456789abcdef0123456789abcdef0123456789abcdef0',
    logged_at: '2024-03-01T09:00:00Z'
  },
  {
    id: 'log-2',
    property_id: 'prop-243',
    mandate_number: 243,
    action_type: 'creation',
    previous_state: null,
    new_state: {
      mandate_number: 243,
      title: 'SALON 1km CENTRE: APPARTEMENT T1 - PARKING LIBRE FAIBLES CHARGES',
      price_fai: 95000,
      status: 'actif'
    },
    performed_by: 'Niels Fernandez',
    signature_sha256: 'b2c3d4e5f6a17890123456789abcdef0123456789abcdef0123456789abcdef0',
    logged_at: '2024-03-02T10:15:00Z'
  }
];

export const MOCK_DVF_TRANSACTIONS: DVFTransaction[] = [
  {
    id: 'dvf-1',
    date_mutation: '2024-01-12',
    valeur_fonciere: 750000,
    adresse_numero: '12',
    adresse_nom_voie: 'Chemin des Viougues',
    code_postal: '13300',
    nom_commune: 'Salon-de-Provence',
    type_local: 'Maison',
    surface_reelle_bati: 165,
    nombre_pieces_principales: 6,
    surface_terrain: 450,
    prix_m2: 4545,
    distance_metres: 120
  },
  {
    id: 'dvf-2',
    date_mutation: '2023-11-20',
    valeur_fonciere: 540000,
    adresse_numero: '8',
    adresse_nom_voie: 'Avenue des Enjouvènes',
    code_postal: '13330',
    nom_commune: 'Pélissanne',
    type_local: 'Maison',
    surface_reelle_bati: 195,
    nombre_pieces_principales: 6,
    surface_terrain: 1200,
    prix_m2: 2769,
    distance_metres: 350
  },
  {
    id: 'dvf-3',
    date_mutation: '2023-10-05',
    valeur_fonciere: 150000,
    adresse_numero: '45',
    adresse_nom_voie: 'Boulevard de la République',
    code_postal: '13300',
    nom_commune: 'Salon-de-Provence',
    type_local: 'Appartement',
    surface_reelle_bati: 55,
    nombre_pieces_principales: 2,
    prix_m2: 2727,
    distance_metres: 600
  }
];

export const INITIAL_CONTACT_LEADS: ContactLead[] = [
  {
    id: 'lead-1',
    name: 'Laurent Mercier',
    email: 'laurent.mercier@orange.fr',
    phone: '06 88 12 34 56',
    message: "Bonjour, je souhaiterais visiter la maison contemporaine aux Viougues (Réf 244) ce samedi si possible. Bien cordialement.",
    subject: "Demande de visite - Réf 244",
    property_id: 'prop-227',
    property_title: 'SALON - LES VIOUGUES: Maison contemporaine 170m²',
    status: 'nouveau',
    created_at: '2024-03-20T14:30:00Z'
  },
  {
    id: 'lead-2',
    name: 'Nathalie Bonnet',
    email: 'n.bonnet13@gmail.com',
    phone: '06 11 22 33 44',
    message: "Bonjour Nelly, nous avons vu la superbe maison de charme au centre de Pélissanne (Réf 235). Pourriez-vous nous transmettre le dossier complet et nous indiquer les disponibilités pour une visite ?",
    subject: "Demande d'information - Réf 235",
    property_id: 'prop-235',
    property_title: 'PÉLISSANNE CENTRE: Superbe Maison de charme 216m²',
    status: 'nouveau',
    created_at: '2024-03-21T09:15:00Z'
  }
];

export const INITIAL_ESTIMATION_LEADS: EstimationLead[] = [
  {
    id: 'est-1',
    first_name: 'Stéphane',
    last_name: 'Dumas',
    email: 's.dumas@bbox.fr',
    phone: '06 55 44 33 22',
    property_type: 'maison',
    city: 'Pélissanne',
    address: 'Chemin des Grands Prés',
    living_area: 145,
    land_area: 900,
    rooms_count: 5,
    has_pool: true,
    status: 'nouveau',
    created_at: '2024-03-19T17:40:00Z'
  },
  {
    id: 'est-2',
    first_name: 'Émilie',
    last_name: 'Roux',
    email: 'emilie.roux@sfr.fr',
    phone: '06 99 88 77 66',
    property_type: 'appartement',
    city: 'Salon-de-Provence',
    address: 'Place Morgan',
    living_area: 68,
    rooms_count: 3,
    has_pool: false,
    status: 'en_cours',
    created_at: '2024-03-18T11:00:00Z'
  }
];

export const INITIAL_TRANSACTIONS: TransactionDeal[] = [
  {
    id: 'trans-1',
    property_id: 'prop-227',
    buyer_id: 'buyer-1',
    status: 'attente_pret',
    offer_price_fai: 730000,
    offer_price_net: 700000,
    agency_fees_amount: 30000,
    deposit_amount: 35000,
    deposit_holder: 'Étude Notariale de Pélissanne (Me Bertrand)',
    seller_name: 'Jean-Pierre & Martine DUPONT',
    seller_phone: '06 12 34 56 78',
    seller_email: 'jp.dupont@orange.fr',
    buyer_name: 'Thomas & Sophie LEFEBVRE',
    buyer_phone: '06 88 77 66 55',
    buyer_email: 'thomas.lefebvre@gmail.com',
    seller_notary_name: 'Me Bertrand VIDAL',
    seller_notary_email: 'vidal.notaire@notaires.fr',
    seller_notary_phone: '04 90 55 12 34',
    seller_notary_office: 'Office Notarial de Pélissanne',
    buyer_notary_name: 'Me Caroline MARTIN',
    buyer_notary_email: 'c.martin@notaires.fr',
    buyer_notary_phone: '04 90 56 78 90',
    buyer_notary_office: 'Étude Notariale Salon République',
    offer_date: '2026-01-15',
    compromis_date: '2026-01-28',
    sru_notification_date: '2026-01-29',
    sru_expiry_date: '2026-02-09',
    loan_application_deadline: '2026-02-28',
    loan_approval_deadline: '2026-03-15',
    final_deed_target_date: '2026-04-10',
    loan_amount_requested: 550000,
    loan_interest_rate_max: 3.45,
    loan_duration_years: 25,
    loan_bank_name: 'BNP Paribas Salon-de-Provence',
    broker_name: 'Meilleurtaux Salon',
    checklist_documents: {
      titre_propriete: true,
      taxe_fonciere: true,
      dossier_diagnostics: true,
      audit_energetique: false,
      pre_etat_date: false,
      reglement_copro: false,
      cni_vendeur: true,
      cni_acquereur: true,
      justificatif_domicile: true,
      simulation_pret: true,
      offre_achat_signee: true
    },
    invoice_number: 'FACT-2026-004',
    invoice_date: '2026-04-10',
    invoice_sent_to_notary: false,
    fees_received: false,
    google_review_requested: false,
    notes: 'Alerte J-10 accord de prêt : relancer le courtier Meilleurtaux Salon pour confirmation de validation des offres.',
    created_at: '2026-01-15T10:00:00Z',
    updated_at: '2026-02-15T14:30:00Z'
  },
  {
    id: 'trans-2',
    property_id: 'prop-235',
    buyer_id: 'buyer-2',
    status: 'acte_planifie',
    offer_price_fai: 495000,
    offer_price_net: 475000,
    agency_fees_amount: 20000,
    deposit_amount: 25000,
    deposit_holder: 'Office Notarial de Salon',
    seller_name: 'Mme Valérie BLANCHARD',
    seller_phone: '06 23 45 67 89',
    seller_email: 'v.blanchard@sfr.fr',
    buyer_name: 'Julien & Camille MOREAU',
    buyer_phone: '06 34 56 78 90',
    buyer_email: 'julien.moreau@free.fr',
    seller_notary_name: 'Me Jean-Luc FAURE',
    seller_notary_email: 'faure.notaires@notaires.fr',
    seller_notary_phone: '04 90 56 11 22',
    seller_notary_office: 'Notaires Associés Place Morgan',
    offer_date: '2025-11-10',
    compromis_date: '2025-11-25',
    sru_notification_date: '2025-11-26',
    sru_expiry_date: '2025-12-08',
    loan_application_deadline: '2025-12-24',
    loan_approval_deadline: '2026-01-20',
    final_deed_target_date: '2026-03-12',
    loan_amount_requested: 380000,
    loan_interest_rate_max: 3.60,
    loan_duration_years: 20,
    loan_bank_name: 'Crédit Agricole Pélissanne',
    checklist_documents: {
      titre_propriete: true,
      taxe_fonciere: true,
      dossier_diagnostics: true,
      audit_energetique: true,
      pre_etat_date: false,
      reglement_copro: false,
      cni_vendeur: true,
      cni_acquereur: true,
      justificatif_domicile: true,
      simulation_pret: true,
      offre_achat_signee: true
    },
    invoice_number: 'FACT-2026-003',
    invoice_date: '2026-03-05',
    invoice_sent_to_notary: true,
    fees_received: false,
    google_review_requested: false,
    notes: 'Signature fixée le 12 mars à 15h00. Relecture du projet d’acte effectuée avec Me Faure.',
    created_at: '2025-11-10T14:00:00Z',
    updated_at: '2026-02-20T11:00:00Z'
  },
  {
    id: 'trans-3',
    property_id: 'prop-243',
    status: 'acte_signe',
    offer_price_fai: 95000,
    offer_price_net: 89000,
    agency_fees_amount: 6000,
    deposit_amount: 5000,
    deposit_holder: 'Me Bertrand VIDAL (Pélissanne)',
    seller_name: 'M. Henri GIRAUD',
    seller_phone: '06 99 88 11 22',
    seller_email: 'henri.giraud@wanadoo.fr',
    buyer_name: 'Romain BOURGEOIS (Investisseur)',
    buyer_phone: '06 77 66 55 44',
    buyer_email: 'romain.bourgeois@gmail.com',
    seller_notary_name: 'Me Bertrand VIDAL',
    seller_notary_email: 'vidal.notaire@notaires.fr',
    seller_notary_phone: '04 90 55 12 34',
    seller_notary_office: 'Office Notarial de Pélissanne',
    offer_date: '2025-10-01',
    compromis_date: '2025-10-18',
    sru_notification_date: '2025-10-19',
    sru_expiry_date: '2025-10-30',
    loan_application_deadline: '2025-11-20',
    loan_approval_deadline: '2025-12-15',
    final_deed_target_date: '2026-01-22',
    actual_closing_date: '2026-01-22',
    checklist_documents: {
      titre_propriete: true,
      taxe_fonciere: true,
      dossier_diagnostics: true,
      audit_energetique: false,
      pre_etat_date: true,
      reglement_copro: true,
      cni_vendeur: true,
      cni_acquereur: true,
      justificatif_domicile: true,
      simulation_pret: true,
      offre_achat_signee: true
    },
    invoice_number: 'FACT-2026-001',
    invoice_date: '2026-01-22',
    invoice_sent_to_notary: true,
    fees_received: true,
    google_review_requested: true,
    notes: 'Acte signé le 22/01. Honoraires de 6 000 € encaissés le 24/01. Avis 5 étoiles Google reçu !',
    created_at: '2025-10-01T09:30:00Z',
    updated_at: '2026-01-25T16:00:00Z'
  }
];

export const INITIAL_PROSPECTING_LEADS: ProspectingLead[] = [
  {
    id: 'pige-1',
    source: 'pap',
    source_url: 'https://www.pap.fr/annonces/maison-pelissanne-13330-r44120',
    title: 'Villa provençale 135m² sur 950m² de terrain arboré avec piscine',
    property_type: 'maison',
    city: 'Pélissanne',
    postal_code: '13330',
    price_asked: 460000,
    initial_price: 495000,
    price_drops_count: 1,
    living_area: 135,
    land_area: 950,
    rooms_count: 5,
    bedrooms_count: 3,
    description: 'Particulier vend villa traditionnelle de plain-pied, quartier calme à 1,5km du centre. Séjour lumineux de 42m² avec cheminée, cuisine équipée indépendante, 3 chambres, garage, piscine 8x4m avec terrasse ombragée. Agences s\'abstenir impérativement.',
    photos_urls: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80'
    ],
    seller_name: 'M. Jean-Luc DUBOIS',
    seller_phone: '06 14 25 36 47',
    seller_email: 'jeanluc.dubois13@gmail.com',
    status: 'a_rappeler',
    call_attempts_count: 2,
    last_contacted_at: '2026-02-28T14:30:00Z',
    next_followup_date: '2026-03-05',
    notes: 'Premier contact le 28/02. A d\'abord refusé par principe, mais a reconnu que depuis sa baisse de 35 000€ il n\'a eu que 2 visites non finançables. D\'accord pour que je lui prépare une estimation comparative DVF de sa rue.',
    estimated_dvf_m2: 3250,
    estimated_dvf_price: 438000,
    days_online: 82,
    created_at: '2025-12-10T10:00:00Z'
  },
  {
    id: 'pige-2',
    source: 'leboncoin',
    source_url: 'https://www.leboncoin.fr/ad/ventes_immobilieres/298412450.htm',
    title: 'Maison contemporaine rénovée 110m² - Quartier Viougues',
    property_type: 'maison',
    city: 'Salon-de-Provence',
    postal_code: '13300',
    price_asked: 365000,
    price_drops_count: 0,
    living_area: 110,
    land_area: 380,
    rooms_count: 4,
    bedrooms_count: 3,
    description: 'En direct propriétaire : maison coup de cœur entièrement rénovée avec goût en 2024. Climatisation réversible, suite parentale en rez-de-chaussée, jardin sans vis-à-vis. DPE classe B.',
    photos_urls: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80'
    ],
    seller_name: 'Mme Sophie ROUX',
    seller_phone: '06 88 77 44 11',
    seller_email: 'sophie.roux.salon@gmail.com',
    status: 'nouveau',
    call_attempts_count: 0,
    notes: 'Annonce mise en ligne il y a 36 heures. Quartier très recherché par nos acquéreurs famille (budget 350-380k€). Appel prioritaire à passer avec le script d\'accroche Nell\'Immo.',
    estimated_dvf_m2: 3280,
    estimated_dvf_price: 360000,
    days_online: 2,
    created_at: '2026-03-01T08:00:00Z'
  },
  {
    id: 'pige-3',
    source: 'pap',
    source_url: 'https://www.pap.fr/annonces/maison-lambesc-13410-r44199',
    title: 'Propriété de charme avec dépendance et oliveraie 180m²',
    property_type: 'maison',
    city: 'Lambesc',
    postal_code: '13410',
    price_asked: 675000,
    initial_price: 720000,
    price_drops_count: 1,
    living_area: 180,
    land_area: 2500,
    rooms_count: 7,
    bedrooms_count: 4,
    description: 'Vends superbe mas rénové sur terrain de 2500m² avec 30 oliviers centenaires. Grande terrasse, vue sur les collines, piscine chauffée. Pas d\'agences merci.',
    photos_urls: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80'
    ],
    seller_name: 'Dr. Marc BENOIT',
    seller_phone: '06 50 60 70 80',
    seller_email: 'marc.benoit.med@gmail.com',
    status: 'rdv_pris',
    call_attempts_count: 3,
    last_contacted_at: '2026-03-01T17:00:00Z',
    next_followup_date: '2026-03-06',
    notes: 'RDV d\'estimation fixé le vendredi 6 mars à 14h30. Les propriétaires déménagent en région lyonnaise et sont fatigués de gérer les curieux le week-end.',
    estimated_dvf_m2: 3600,
    estimated_dvf_price: 648000,
    days_online: 74,
    created_at: '2025-12-18T11:00:00Z'
  },
  {
    id: 'pige-4',
    source: 'boitage',
    title: 'Maison traditionnelle quartier Les Costes - Contact Boîtage',
    property_type: 'maison',
    city: 'Pélissanne',
    postal_code: '13330',
    price_asked: 410000,
    price_drops_count: 0,
    living_area: 120,
    land_area: 600,
    rooms_count: 5,
    bedrooms_count: 3,
    description: 'Propriétaire ayant contacté l\'agence suite au flyer déposé dans sa boîte aux lettres. Projet de vente pour départ en retraite d\'ici fin 2026.',
    photos_urls: [],
    seller_name: 'M. et Mme ROUSTAN',
    seller_phone: '04 90 55 89 22',
    status: 'nouveau',
    call_attempts_count: 1,
    last_contacted_at: '2026-02-27T10:00:00Z',
    next_followup_date: '2026-03-04',
    notes: 'Très bon accueil au téléphone. Préfèrent confier l\'exclusivité à une agence locale de Pélissanne plutôt qu\'à un grand réseau national.',
    estimated_dvf_m2: 3300,
    estimated_dvf_price: 396000,
    days_online: 5,
    created_at: '2026-02-25T14:00:00Z'
  }
];

export const INITIAL_AGENCY_KEYS: AgencyKey[] = [
  {
    id: 'key-1',
    property_id: 'prop-227',
    keyring_number: 244,
    cabinet_location: 'Armoire A • Rgt 01',
    keys_count: 3,
    has_alarm_badge: true,
    status: 'disponible',
    notes: 'Trousseau complet : Portail coulissant, porte entrée sécurité 5 points, porte de garage motorisé + badge Vigik alarme.',
    created_at: '2025-10-06T09:00:00Z'
  },
  {
    id: 'key-2',
    property_id: 'prop-228',
    keyring_number: 228,
    cabinet_location: 'Armoire A • Rgt 02',
    keys_count: 2,
    has_alarm_badge: false,
    status: 'prete',
    current_borrower: {
      id: 'loan-1',
      key_id: 'key-2',
      borrower_name: 'Jean-Luc Morvan',
      borrower_phone: '06 12 34 56 78',
      borrower_company: 'DiagMéditerranée SAS',
      borrower_role: 'diagnostiqueur',
      borrowed_at: new Date(Date.now() - 3600000 * 24).toISOString(),
      expected_return_at: new Date(Date.now() + 3600000 * 6).toISOString(),
      purpose: 'Réalisation du métrage Loi Carrez et mise à jour de l\'audit énergétique',
      discharged: true
    },
    loan_history: [
      {
        id: 'loan-1',
        key_id: 'key-2',
        borrower_name: 'Jean-Luc Morvan',
        borrower_phone: '06 12 34 56 78',
        borrower_company: 'DiagMéditerranée SAS',
        borrower_role: 'diagnostiqueur',
        borrowed_at: new Date(Date.now() - 3600000 * 24).toISOString(),
        expected_return_at: new Date(Date.now() + 3600000 * 6).toISOString(),
        purpose: 'Réalisation du métrage Loi Carrez et mise à jour de l\'audit énergétique',
        discharged: true
      }
    ],
    notes: 'Prêt en cours au diagnostiqueur agréé.',
    created_at: '2025-09-12T10:00:00Z'
  },
  {
    id: 'key-3',
    property_id: 'prop-229',
    keyring_number: 229,
    cabinet_location: 'Armoire B • Rgt 05',
    keys_count: 4,
    has_alarm_badge: true,
    status: 'disponible',
    notes: 'Clés maison de village Lambesc (Porte principale, cave voûtée, atelier jardin).',
    created_at: '2025-11-04T11:30:00Z'
  },
  {
    id: 'key-4',
    property_id: 'prop-230',
    keyring_number: 230,
    cabinet_location: 'Armoire B • Rgt 06',
    keys_count: 1,
    has_alarm_badge: false,
    status: 'double_proprietaire',
    notes: 'Le propriétaire réside sur place, double de secours d\'agence pour visites accompagnées.',
    created_at: '2026-01-08T14:15:00Z'
  }
];

export const INITIAL_AGENCY_SIGNBOARDS: AgencySignboard[] = [
  {
    id: 'sign-1',
    property_id: 'prop-227',
    signboard_type: 'exclusivite',
    status: 'pose',
    installed_at: '2025-10-10',
    location_details: 'Portail d\'entrée sur voie publique, Les Viougues, Salon-de-Provence',
    notes: 'Panneau Akilux 80x60 cm avec œillets et colliers de serrage renforcés.',
    created_at: '2025-10-10T10:00:00Z'
  },
  {
    id: 'sign-2',
    property_id: 'prop-228',
    signboard_type: 'vendu',
    status: 'a_deposer',
    installed_at: '2025-11-15',
    removal_deadline: new Date(Date.now() + 3600000 * 24 * 4).toISOString().slice(0, 10),
    location_details: 'Clôture sur avenue principale, Pélissanne',
    notes: 'Réglementation Loi Grenelle II : dépose obligatoire sous 3 mois après la signature de l\'acte authentique.',
    created_at: '2025-11-15T09:00:00Z'
  },
  {
    id: 'sign-3',
    property_id: 'prop-229',
    signboard_type: 'a_vendre',
    status: 'pose',
    installed_at: '2026-01-18',
    location_details: 'Façade sur rue commerçante, Lambesc',
    notes: 'Panneau en V pour double visibilité piétonne et routière.',
    created_at: '2026-01-18T14:00:00Z'
  },
  {
    id: 'sign-4',
    signboard_type: 'a_vendre',
    status: 'en_stock',
    location_details: 'Réserve Agence Nell\'Immo',
    notes: 'Panneau neuf prêt pour nouveau mandat exclusif.',
    created_at: '2026-02-01T08:00:00Z'
  },
  {
    id: 'sign-5',
    signboard_type: 'vendu',
    status: 'en_stock',
    location_details: 'Réserve Agence Nell\'Immo',
    notes: 'Panneau VENDU réutilisable en parfait état.',
    created_at: '2026-02-01T08:00:00Z'
  }
];

export const INITIAL_MANDATE_AVENANTS: MandateAvenant[] = [
  {
    id: 'avenant-1',
    mandate_number: 244,
    property_id: 'prop-227',
    avenant_number: 1,
    avenant_type: 'baisse_prix',
    previous_price_fai: 815000,
    new_price_fai: 786600,
    previous_price_net: 782400,
    new_price_net: 755136,
    previous_fees_amount: 32600,
    new_fees_amount: 31464,
    reason: 'Repositionnement tarifaire après 4 visites qualifiées pour dynamiser les offres avant le printemps.',
    effective_date: '2025-11-20',
    is_signed: true,
    signed_at: '2025-11-20T14:30:00Z',
    signature_sha256: '9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f8e',
    created_at: '2025-11-20T14:00:00Z'
  }
];

export const INITIAL_PROPOSALS: ProposalHistory[] = [
  {
    id: 'prop-hist-1',
    property_id: 'prop-227',
    buyer_id: 'buyer-1',
    proposed_at: '2026-02-15T10:00:00Z',
    channel: 'whatsapp',
    status: 'interesse',
    feedback: 'Très enthousiaste sur la pièce de vie de 65m² et la piscine. Visite programmée avec succès.'
  },
  {
    id: 'prop-hist-2',
    property_id: 'prop-227',
    buyer_id: 'buyer-2',
    proposed_at: '2026-02-18T15:30:00Z',
    channel: 'email',
    status: 'refuse',
    feedback: 'Recherche une parcelle plus vaste (> 1 000 m²) pour chevaux.'
  }
];
