import type { DVFTransaction } from './types';

/**
 * Jeu de données DVF de démonstration (source : simulation locale).
 * Ces actes notariés sont fictifs mais réalistes pour Pélissanne / Salon-de-Provence / Lambesc.
 * Ce fichier est isolé afin de ne contenir AUCUNE donnée personnelle (PII) d'acquéreurs,
 * évitant toute fuite dans les bundles publics (ex: Espace Vendeur).
 */
export const MOCK_DVF_TRANSACTIONS: DVFTransaction[] = [
  // --- Pélissanne (13330) — maisons ---
  {
    id: 'dvf-1',
    date_mutation: '2024-01-12',
    valeur_fonciere: 750000,
    adresse_numero: '12',
    adresse_nom_voie: 'Chemin des Viougues',
    code_postal: '13330',
    nom_commune: 'Pélissanne',
    type_local: 'Maison',
    surface_reelle_bati: 165,
    nombre_pieces_principales: 6,
    surface_terrain: 450,
    prix_m2: 4545,
    distance_metres: 120
  },
  {
    id: 'dvf-2',
    date_mutation: '2023-11-20',
    valeur_fonciere: 540000,
    adresse_numero: '8',
    adresse_nom_voie: 'Avenue des Enjouvènes',
    code_postal: '13330',
    nom_commune: 'Pélissanne',
    type_local: 'Maison',
    surface_reelle_bati: 195,
    nombre_pieces_principales: 6,
    surface_terrain: 1200,
    prix_m2: 2769,
    distance_metres: 350
  },
  {
    id: 'dvf-4',
    date_mutation: '2024-02-18',
    valeur_fonciere: 615000,
    adresse_numero: '27',
    adresse_nom_voie: 'Chemin des Grands Prés',
    code_postal: '13330',
    nom_commune: 'Pélissanne',
    type_local: 'Maison',
    surface_reelle_bati: 178,
    nombre_pieces_principales: 5,
    surface_terrain: 900,
    prix_m2: 3455,
    distance_metres: 210
  },
  {
    id: 'dvf-5',
    date_mutation: '2023-09-14',
    valeur_fonciere: 468000,
    adresse_numero: '5',
    adresse_nom_voie: 'Impasse des Lavandes',
    code_postal: '13330',
    nom_commune: 'Pélissanne',
    type_local: 'Maison',
    surface_reelle_bati: 142,
    nombre_pieces_principales: 4,
    surface_terrain: 620,
    prix_m2: 3296,
    distance_metres: 480
  },
  {
    id: 'dvf-6',
    date_mutation: '2024-03-02',
    valeur_fonciere: 820000,
    adresse_numero: '3',
    adresse_nom_voie: 'Chemin de la Crau',
    code_postal: '13330',
    nom_commune: 'Pélissanne',
    type_local: 'Maison',
    surface_reelle_bati: 210,
    nombre_pieces_principales: 7,
    surface_terrain: 1500,
    prix_m2: 3905,
    distance_metres: 560
  },
  // --- Pélissanne (13330) — appartements ---
  {
    id: 'dvf-7',
    date_mutation: '2023-12-05',
    valeur_fonciere: 198000,
    adresse_numero: '14',
    adresse_nom_voie: 'Avenue de la République',
    code_postal: '13330',
    nom_commune: 'Pélissanne',
    type_local: 'Appartement',
    surface_reelle_bati: 68,
    nombre_pieces_principales: 3,
    prix_m2: 2912,
    distance_metres: 300
  },
  {
    id: 'dvf-8',
    date_mutation: '2024-01-28',
    valeur_fonciere: 245000,
    adresse_numero: '22',
    adresse_nom_voie: 'Rue Jean Jaurès',
    code_postal: '13330',
    nom_commune: 'Pélissanne',
    type_local: 'Appartement',
    surface_reelle_bati: 82,
    nombre_pieces_principales: 4,
    prix_m2: 2988,
    distance_metres: 640
  },
  // --- Salon-de-Provence (13300) ---
  {
    id: 'dvf-9',
    date_mutation: '2023-10-05',
    valeur_fonciere: 150000,
    adresse_numero: '45',
    adresse_nom_voie: 'Boulevard de la République',
    code_postal: '13300',
    nom_commune: 'Salon-de-Provence',
    type_local: 'Appartement',
    surface_reelle_bati: 55,
    nombre_pieces_principales: 2,
    prix_m2: 2727,
    distance_metres: 600
  },
  {
    id: 'dvf-10',
    date_mutation: '2024-02-09',
    valeur_fonciere: 385000,
    adresse_numero: '18',
    adresse_nom_voie: 'Avenue Aristide Briand',
    code_postal: '13300',
    nom_commune: 'Salon-de-Provence',
    type_local: 'Maison',
    surface_reelle_bati: 128,
    nombre_pieces_principales: 4,
    surface_terrain: 380,
    prix_m2: 3008,
    distance_metres: 720
  },
  {
    id: 'dvf-11',
    date_mutation: '2023-11-30',
    valeur_fonciere: 690000,
    adresse_numero: '9',
    adresse_nom_voie: 'Chemin du Vallon',
    code_postal: '13300',
    nom_commune: 'Salon-de-Provence',
    type_local: 'Maison',
    surface_reelle_bati: 190,
    nombre_pieces_principales: 6,
    surface_terrain: 1100,
    prix_m2: 3632,
    distance_metres: 850
  },
  {
    id: 'dvf-12',
    date_mutation: '2024-03-15',
    valeur_fonciere: 172000,
    adresse_numero: '31',
    adresse_nom_voie: 'Rue du Maréchal Joffre',
    code_postal: '13300',
    nom_commune: 'Salon-de-Provence',
    type_local: 'Appartement',
    surface_reelle_bati: 61,
    nombre_pieces_principales: 3,
    prix_m2: 2820,
    distance_metres: 940
  },
  // --- Lambesc (13410) ---
  {
    id: 'dvf-13',
    date_mutation: '2023-12-18',
    valeur_fonciere: 720000,
    adresse_numero: '6',
    adresse_nom_voie: 'Chemin des Oliviers',
    code_postal: '13410',
    nom_commune: 'Lambesc',
    type_local: 'Maison',
    surface_reelle_bati: 205,
    nombre_pieces_principales: 6,
    surface_terrain: 1800,
    prix_m2: 3512,
    distance_metres: 150
  },
  {
    id: 'dvf-14',
    date_mutation: '2024-01-22',
    valeur_fonciere: 540000,
    adresse_numero: '11',
    adresse_nom_voie: 'Route de Rognes',
    code_postal: '13410',
    nom_commune: 'Lambesc',
    type_local: 'Maison',
    surface_reelle_bati: 158,
    nombre_pieces_principales: 5,
    surface_terrain: 950,
    prix_m2: 3418,
    distance_metres: 420
  }
];
